export type CompanyService = {
  id: string;
  nameEn: string;
  nameVi: string;
  descriptionEn: string;
  descriptionVi: string;
  scopeEn: string;
  scopeVi: string;
  processEn: string;
  processVi: string;
};

export const company = {
  brandName: "TRIEU HY MEDIA",
  legalNameVi: "CÔNG TY TNHH TRUYỀN THÔNG TRIỆU HỶ",
  legalNameEn: "TRIEU HY MEDIA COMPANY LIMITED",
  shortName: "TRIEU HY MEDIA CO.,LTD",
  businessId: "0402340888",
  registrationDateVi: "28/05/2026",
  registrationDateEn: "May 28, 2026",
  registrationDateIso: "2026-05-28",
  operationStatusVi: "Đang hoạt động",
  operationStatusEn: "Active",
  companyTypeVi: "Công ty trách nhiệm hữu hạn ngoài nhà nước",
  companyTypeEn: "Non-state limited liability company",
  representativeVi: "ĐỖ THỊ THANH LÝ",
  representativeEn: "DO THI THANH LY",
  representativeTitle: "Director",
  addressVi: "77 Thanh Lương 8, Phường Hòa Xuân, Thành phố Đà Nẵng, Việt Nam",
  addressEn: "77 Thanh Luong 8, Hoa Xuan Ward, Da Nang City, Vietnam",
  phoneDisplay: "0961 499 943",
  phoneInternational: "+84 961 499 943",
  phoneHref: "tel:+84961499943",
  phoneSchema: "+84961499943",
  email: "admin@trieuhymedia.com",
  website: "https://trieuhymedia.net",
  primaryBusinessActivityVi: "Quảng cáo",
  primaryBusinessActivityEn: "Advertising",
  socialLinks: [] as { label: string; href: string }[],
  privacyEffectiveDate: "July 16, 2026",
  privacyEffectiveDateVi: "16/07/2026",
  structuredAddress: {
    streetAddress: "77 Thanh Luong 8",
    addressLocality: "Da Nang City",
    addressRegion: "Da Nang",
    addressCountry: "VN",
  },
  showRepresentative: true,
  showPhone: true,
  showVietnameseLegalName: true,
  services: [
    {
      id: "advertising-strategy",
      nameEn: "Advertising Strategy",
      nameVi: "Chiến lược quảng cáo",
      descriptionEn: "Planning practical advertising directions based on the communication goals, audience and available resources of each business.",
      descriptionVi: "Xây dựng định hướng quảng cáo thực tế dựa trên mục tiêu truyền thông, đối tượng khách hàng và nguồn lực của từng doanh nghiệp.",
      scopeEn: "Communication objectives, audience definition, channel direction and practical priorities.",
      scopeVi: "Mục tiêu truyền thông, xác định đối tượng, định hướng kênh và các ưu tiên thực tế.",
      processEn: "Brief review, objective alignment, direction planning and recommendation delivery.",
      processVi: "Tiếp nhận thông tin, thống nhất mục tiêu, lập định hướng và bàn giao đề xuất.",
    },
    {
      id: "brand-communication",
      nameEn: "Brand Communication",
      nameVi: "Truyền thông thương hiệu",
      descriptionEn: "Supporting businesses in presenting a consistent, clear and professional brand message across communication channels.",
      descriptionVi: "Hỗ trợ doanh nghiệp truyền tải thông điệp thương hiệu nhất quán, rõ ràng và chuyên nghiệp trên các kênh truyền thông.",
      scopeEn: "Core messages, communication tone, content alignment and channel consistency.",
      scopeVi: "Thông điệp cốt lõi, giọng điệu truyền thông, định hướng nội dung và tính nhất quán giữa các kênh.",
      processEn: "Message review, communication framework, content guidance and final alignment.",
      processVi: "Rà soát thông điệp, xây dựng khung truyền thông, hướng dẫn nội dung và thống nhất hoàn thiện.",
    },
    {
      id: "creative-content",
      nameEn: "Creative Content",
      nameVi: "Nội dung sáng tạo",
      descriptionEn: "Developing content concepts and communication materials suited to business campaigns and brand identity.",
      descriptionVi: "Phát triển ý tưởng nội dung và tài liệu truyền thông phù hợp với chiến dịch và nhận diện thương hiệu.",
      scopeEn: "Content concepts, campaign copy, presentation materials and brand-aligned content.",
      scopeVi: "Ý tưởng nội dung, nội dung chiến dịch, tài liệu giới thiệu và nội dung phù hợp với thương hiệu.",
      processEn: "Content brief, concept development, drafting, refinement and delivery.",
      processVi: "Tiếp nhận yêu cầu, phát triển ý tưởng, biên soạn, hiệu chỉnh và bàn giao.",
    },
    {
      id: "digital-advertising-support",
      nameEn: "Digital Advertising Support",
      nameVi: "Hỗ trợ quảng cáo số",
      descriptionEn: "Assisting with the preparation, coordination and improvement of digital advertising activities.",
      descriptionVi: "Hỗ trợ chuẩn bị, phối hợp và cải thiện các hoạt động quảng cáo trên nền tảng số.",
      scopeEn: "Campaign preparation, content coordination, asset readiness and activity review.",
      scopeVi: "Chuẩn bị chiến dịch, phối hợp nội dung, hoàn thiện tài liệu và rà soát hoạt động.",
      processEn: "Requirement review, preparation plan, coordinated execution and improvement notes.",
      processVi: "Rà soát yêu cầu, lập kế hoạch chuẩn bị, phối hợp triển khai và đề xuất cải thiện.",
    },
    {
      id: "communication-design",
      nameEn: "Communication Design",
      nameVi: "Thiết kế truyền thông",
      descriptionEn: "Creating visual communication materials for advertising, campaigns and business presentations.",
      descriptionVi: "Thiết kế các ấn phẩm hình ảnh phục vụ quảng cáo, chiến dịch và hoạt động giới thiệu doanh nghiệp.",
      scopeEn: "Campaign visuals, communication layouts, digital materials and business presentations.",
      scopeVi: "Hình ảnh chiến dịch, bố cục truyền thông, tài liệu số và bài trình bày doanh nghiệp.",
      processEn: "Design brief, visual direction, production, feedback and final files.",
      processVi: "Tiếp nhận yêu cầu, xác lập hướng hình ảnh, thiết kế, phản hồi và bàn giao.",
    },
    {
      id: "campaign-coordination",
      nameEn: "Campaign Coordination",
      nameVi: "Phối hợp chiến dịch",
      descriptionEn: "Supporting advertising campaigns from initial planning through execution and post-campaign review.",
      descriptionVi: "Hỗ trợ chiến dịch quảng cáo từ giai đoạn lập kế hoạch, triển khai đến đánh giá sau chiến dịch.",
      scopeEn: "Planning coordination, timeline alignment, communication materials and review support.",
      scopeVi: "Phối hợp kế hoạch, thống nhất tiến độ, tài liệu truyền thông và hỗ trợ đánh giá.",
      processEn: "Planning, coordination, execution support, progress review and closing notes.",
      processVi: "Lập kế hoạch, phối hợp, hỗ trợ triển khai, rà soát tiến độ và tổng kết.",
    },
    {
      id: "digital-product-operations",
      nameEn: "Digital Product Operations — CocoDrama",
      nameVi: "Vận hành sản phẩm số — CocoDrama",
      descriptionEn: "Operating CocoDrama, a short-form drama product that brings licensed content and localized viewing experiences to audiences in Southeast Asia.",
      descriptionVi: "Vận hành CocoDrama — sản phẩm phim ngắn đưa nội dung có bản quyền và trải nghiệm xem được bản địa hóa đến khán giả Đông Nam Á.",
      scopeEn: "Product experience, content release coordination, localization support, subscription access and advertising-supported episode access.",
      scopeVi: "Trải nghiệm sản phẩm, phối hợp phát hành nội dung, hỗ trợ bản địa hóa, quyền truy cập theo gói và hình thức mở tập bằng quảng cáo.",
      processEn: "Content and product planning, localization coordination, release preparation, platform operation and ongoing review.",
      processVi: "Lập kế hoạch nội dung và sản phẩm, phối hợp bản địa hóa, chuẩn bị phát hành, vận hành nền tảng và rà soát liên tục.",
    },
    {
      id: "hy-garden-workspace",
      nameEn: "Hy Garden Coffee Workspace",
      nameVi: "Hỷ Garden — coffee workspace",
      descriptionEn: "Operating Hy Garden as a coffee shop and work-friendly space, with rental arrangements available for suitable working sessions and gatherings.",
      descriptionVi: "Vận hành Hỷ Garden như một coffee shop và không gian làm việc thân thiện, có bố trí cho thuê phù hợp với nhu cầu làm việc hoặc gặp gỡ.",
      scopeEn: "Coffee service, a work-friendly setting and space-rental arrangements subject to availability and the nature of the booking.",
      scopeVi: "Dịch vụ coffee, không gian hỗ trợ làm việc và phương án cho thuê theo tình trạng chỗ trống cũng như tính chất buổi sử dụng.",
      processEn: "Share your preferred date, group size and intended use; we confirm availability and arrange the suitable setup.",
      processVi: "Chia sẻ ngày dự kiến, số lượng người và nhu cầu sử dụng; đội ngũ sẽ xác nhận tình trạng chỗ và bố trí phù hợp.",
    },
  ] satisfies CompanyService[],
} as const;

export type Company = typeof company;
