import { company } from "@/src/config/company";

export const locales = ["en", "vi", "zh", "ko"] as const;
export type Locale = (typeof locales)[number];

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}

const shared = {
  en: {
    nav: { home: "Home", about: "About", services: "Services", garden: "Hy Garden", cocodrama: "CocoDrama", workshop: "AI Short Drama", contact: "Contact", contactUs: "Contact us", menu: "Menu", close: "Close" },
    footer: { company: "Company", legal: "Legal", rights: "All rights reserved." },
    labels: {
      legalName: "Legal name",
      legalNameVi: "Vietnamese legal name",
      shortName: "Short name",
      businessId: "Business ID / Tax ID",
      registrationDate: "Registration date",
      status: "Status",
      companyType: "Company type",
      activity: "Primary business activity",
      representative: "Legal representative",
      address: "Address",
      phone: "Phone",
      email: "Email",
      website: "Website",
    },
  },
  vi: {
    nav: { home: "Trang chủ", about: "Giới thiệu", services: "Dịch vụ", garden: "Hỷ Garden", cocodrama: "CocoDrama", workshop: "Khóa học AI", contact: "Liên hệ", contactUs: "Liên hệ", menu: "Menu", close: "Đóng" },
    footer: { company: "Doanh nghiệp", legal: "Pháp lý", rights: "Bảo lưu mọi quyền." },
    labels: {
      legalName: "Tên pháp nhân",
      legalNameVi: "Tên pháp nhân tiếng Việt",
      shortName: "Tên viết tắt",
      businessId: "Mã số doanh nghiệp / Mã số thuế",
      registrationDate: "Ngày hoạt động",
      status: "Tình trạng",
      companyType: "Loại hình doanh nghiệp",
      activity: "Ngành nghề chính",
      representative: "Người đại diện pháp luật",
      address: "Địa chỉ",
      phone: "Điện thoại",
      email: "Email",
      website: "Website",
    },
  },
  zh: {
    nav: { home: "首页", about: "关于我们", services: "业务服务", garden: "Hỷ Garden", cocodrama: "CocoDrama", workshop: "AI 短剧特训", contact: "联系我们", contactUs: "联系我们", menu: "菜单", close: "关闭" },
    footer: { company: "公司", legal: "法律信息", rights: "版权所有。" },
    labels: {
      legalName: "法定名称",
      legalNameVi: "越南语法定名称",
      shortName: "简称",
      businessId: "企业编号 / 税号",
      registrationDate: "注册日期",
      status: "经营状态",
      companyType: "企业类型",
      activity: "主营业务",
      representative: "法定代表人",
      address: "地址",
      phone: "电话",
      email: "电子邮箱",
      website: "网站",
    },
  },
  ko: {
    nav: { home: "홈", about: "회사 소개", services: "서비스", garden: "Hỷ Garden", cocodrama: "CocoDrama", workshop: "AI 숏드라마", contact: "문의", contactUs: "문의하기", menu: "메뉴", close: "닫기" },
    footer: { company: "회사", legal: "법률 정보", rights: "All rights reserved." },
    labels: {
      legalName: "법인명", legalNameVi: "베트남어 법인명", shortName: "약칭", businessId: "사업자 번호 / 세금 번호",
      registrationDate: "등록일", status: "상태", companyType: "회사 형태", activity: "주요 사업", representative: "법정 대표자",
      address: "주소", phone: "전화", email: "이메일", website: "웹사이트",
    },
  },
} as const;

const koContent = {
  ...shared.ko,
  home: {
    eyebrow: "기업 공식 웹사이트", headline: "명확한 생각에서 출발하는 창의적 광고", intro: `${company.legalNameEn}는 베트남 다낭에 기반을 둔 합법 등록 광고 회사입니다. 명확한 커뮤니케이션 전략과 창의적인 콘텐츠, 실용적인 광고 솔루션으로 기업을 지원합니다.`, explore: "서비스 살펴보기",
    overviewTitle: "TRIEU HY MEDIA 소개", overview: `${company.legalNameEn}는 ${company.registrationDateEn}에 등록되어 베트남 다낭 호아쑤언 지역에 본사를 두고 있습니다. 광고 분야에서 명확함, 책임감, 전문성을 바탕으로 활동합니다.`, overviewDetail: "회사 오피스, Hy Garden 커피 워크스페이스, CocoDrama와 같은 디지털 제품 개발을 한 공간에 연결해 집중적인 업무와 창의적인 대화를 지원합니다.", overviewImage: "TRIEU HY MEDIA 업무 공간", learnMore: "회사 더 알아보기",
    hyGarden: { eyebrow: "업무 환경", title: "Hỷ Garden — 오피스와 커피 공간", description: "Hỷ Garden은 TRIEU HY MEDIA의 업무 공간과 커피숍이 함께 있는 곳입니다. 집중 업무, 팀 대화, 커피를 곁들인 만남을 위한 편안한 환경을 제공합니다.", note: "일과 소통, 일상의 연결이 자연스럽게 이어지는 실용적인 공간입니다.", cta: "Hỷ Garden 둘러보기", labels: ["TRIEU HY MEDIA 오피스", "커피 워크스페이스", "가든 환경", "상층 업무 공간"] },
    cocodrama: { eyebrow: "디지털 제품", title: "CocoDrama, 동남아 4개 시장을 위한 현지화 숏폼 스토리", description: "정식 라이선스 콘텐츠, 5개 언어 현지화, 구독 또는 광고 기반 에피소드 이용 방식을 제공합니다.", cta: "CocoDrama 살펴보기" },
    servicesTitle: "광고 및 커뮤니케이션 서비스", servicesIntro: "명확한 방향, 일관된 커뮤니케이션, 실용적인 크리에이티브 실행이 필요한 기업을 위한 집중 지원입니다.", approachTitle: "일하는 방식", approach: [["이해", "비즈니스 환경, 목표, 커뮤니케이션 요구를 먼저 듣습니다."], ["계획", "실용적인 방향과 우선순위, 명확한 업무 범위를 정합니다."], ["제작", "합의된 방향에 맞춰 콘텐츠와 자료를 제작합니다."], ["실행", "신중하게 진행을 조율하고 명확히 공유합니다."], ["검토", "결과와 피드백을 확인하고 필요한 부분을 다듬습니다."]], principlesTitle: "업무 원칙", principles: ["명확성", "책임감", "일관성", "창의성", "전문성"], companyTitle: "회사 정보", ctaTitle: "더 명확한 커뮤니케이션을 시작하세요", ctaText: "광고 및 기업 커뮤니케이션 문의는 TRIEU HY MEDIA로 연락해 주세요.", cta: "팀에 문의하기",
  },
  about: { eyebrow: "회사 소개", title: "명확함과 책임감으로 만드는 기업 커뮤니케이션", intro: `${company.legalNameEn}는 베트남 다낭에 본사를 둔 합법 등록 기업입니다. ${company.registrationDateEn}에 사업자 번호 ${company.businessId}로 등록되었습니다.`, sections: [["법적 설립", "회사는 정상 운영 중인 비국영 유한책임회사이며, 등록 사무소는 베트남 다낭 호아쑤언에 있습니다."], ["주요 사업", "회사의 주요 등록 사업은 광고이며, 기업을 위한 실용적인 광고 및 커뮤니케이션 지원에 집중합니다."], ["미션", "실용적인 광고와 커뮤니케이션 솔루션을 통해 기업이 메시지를 전문적으로 전달하도록 돕습니다."], ["업무 원칙", "모든 프로젝트를 명확성, 책임감, 일관성 그리고 고객 목표에 대한 존중으로 대합니다."]], companyTitle: "공식 회사 정보", contactTitle: "연락처" },
  servicesPage: { eyebrow: "서비스", title: "서비스와 운영 분야", intro: "TRIEU HY MEDIA는 광고·커뮤니케이션 지원, CocoDrama 디지털 제품, Hỷ Garden 커피 워크스페이스 운영을 함께 전개합니다.", scope: "지원 범위", process: "기본 프로세스", discuss: "프로젝트 상담", visualTitle: "커뮤니케이션 서비스부터 디지털 제품과 공유 공간까지", visualLabels: ["창의적 기획과 방향 설정", "CocoDrama를 통한 디지털 제품 커뮤니케이션"] },
  workshopPage: {
    eyebrow: "실전 마스터클래스",
    collaboration: "TRIỆU HỶ MEDIA × VŨ LEE | COCO DRAMA",
    title: "AI SHORT DRAMA MAKER",
    courseSubtitle: "AI 영화 제작 실전 마스터클래스",
    headline: "AI 영화 제작 실전 마스터클래스 — Vũ Lee 디렉터 & Triệu Hỷ Media와 함께하는 15회 실전 세션",
    welcome: "AI Short Drama Maker 전문 과정에 오신 것을 환영합니다!",
    description: "스튜디오급 AI 숏폼 드라마 및 애니메이션 제작 파이프라인: AI 각본, 스토리텔링, 스토리보드, 일관된 캐릭터 및 배경 생성, 모션 제어, 편집, Voice AI, 음악, SFX 및 컬러 그레이딩.",
    tuition: {
      title: "수강료 안내 & Coco Drama 장학 혜택",
      badge: "2026 신입 모집",
      originalPrice: "12,000,000 VND/과정",
      originalPriceLabel: "정규 수강료",
      discountPrice: "7,000,000 VND/과정",
      discountPriceLabel: "얼리버드 개강 혜택",
      scholarshipTitle: "Coco Drama Scholarship 장학 프로그램",
      scholarshipSupport: "700만 VND 학비 장학 지원",
      scholarshipNote: "조기 등록 및 숏폼 드라마 제작에 열정을 지닌 수강생을 위한 Coco Drama Scholarship 학비 지원 프로그램. AI 크레딧 지원 및 Coco Drama 상업 숏폼 드라마 제작 프로젝트 직접 참여 기회를 제공합니다.",
      duration: "15회 실전 세션",
      durationLabel: "수업 일정",
      location: "Hỷ Garden - 15 Trung Lương 16, Hòa Xuân, Cẩm Lệ, Đà Nẵng",
      locationLabel: "교육 장소",
      outcomesTitle: "수료 후 4대 핵심 결과물 및 혜택",
      outcomes: [
        "배급 가능한 1편의 완전한 AI 영상 작품 완성",
        "스튜디오급 개인 AI 영화 포트폴리오 구축",
        "Triệu Hỷ Media × Vũ Lee 공식 수료 인증서 발급",
        "Coco Drama 플랫폼 상업 숏폼 드라마 제작 프로젝트 직접 참여 기회",
      ],
      cta: "장학 혜택 및 얼리버드 신청하기",
    },
    instructors: [
      {
        name: "VU LEE",
        title: "발표자 · AI Film Director",
        image: "/workshop/vulee-speaker.jpg",
        bio: "GenAI, Veo 3, Seedance 2.0 및 시네마틱 파이프라인을 상업 영화 및 단편 애니메이션 제작에 도입한 선도적인 전문가.",
      },
      {
        name: "HOÀ NGUYỄN",
        title: "초청 게스트 · AI Creator · Hulk Nón Lá 채널 운영자",
        image: "/workshop/workshop-attendees.jpg",
        bio: "수백만 조회수를 기록한 Hulk Nón Lá 채널의 대표 크리에이터로 비주얼 스토리텔링 및 바이럴 AI 영상 실전 제작 전문가.",
      },
    ],
    stats: [
      { value: "15", label: "실전 수업 회차" },
      { value: "04", label: "집중 단계" },
      { value: "03", label: "주요 실습 프로젝트" },
      { value: "성과", label: "기준을 충족한 수강생에게 주어지는 협업 기회" },
    ],
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdv3mJYRhMJVEKBOkpKrsDyB2xFT0VtI72YIRdY5zV5i_duGA/viewform?usp=send_form",
    ctaRegister: "참가 신청하기",
    openInNewTab: "새 탭에서 신청 양식 열기",
    scanQr: "모바일 QR 코드로 간편 신청",
    curriculumTitle: "15회차 실전 로드맵",
    phases: [
      {
        phaseNumber: "01",
        phaseTitle: "기획 & 시나리오 제작",
        sessions: [
          { sessionNumber: "01", title: "진로 방향 & 도구 준비", tag: "오리엔테이션", items: ["AI 영화 제작 산업 전망 & 진로 방향", "전체 툴셋 소개 & 필수 계정 세팅", "업무 & 영상 제작용 빌드 앱 활용", "졸업 과제 안내: 숏폼 플랫폼용 작품 또는 상업 영상"], tools: ["Gemini", "ChatGPT", "Claude", "Build App"] },
          { sessionNumber: "02", title: "AI 각본 및 시나리오 제작", tag: "시나리오", items: ["전문 툴을 활용한 영화 표준 시나리오 구조화", "멀티 AI(Gemini, ChatGPT, Claude) 프롬프트 최적화", "AI 결과물 종합 및 영화적 각색"], tools: ["Gemini", "ChatGPT", "Claude", "Scriptwriting"] },
          { sessionNumber: "03", title: "스토리보드 AI & 전문 씬 분할", tag: "스토리보드", items: ["AI 스토리보드 생성 & 카메라 앵글/조명 분석", "샷 리스트 및 씬별 브레이크다운 작성", "렌더링 시간 및 제작 일정 수립", "실습: 시나리오 1개 씬을 스토리보드로 변환"], tools: ["Storyboard AI", "Shot List", "Góc Máy", "Pre-production"] },
        ],
      },
      {
        phaseNumber: "02",
        phaseTitle: "캐릭터 생성 & 배경 구축",
        sessions: [
          { sessionNumber: "04", title: "일관된 캐릭터 디자인 & 스튜디오 세팅", tag: "캐릭터", items: ["고화질 AI 캐릭터 디자인 및 다각도 일관성 유지", "프로젝트 캐릭터 라이브러리 구축 및 스튜디오 관리"], tools: ["Character Design", "Consistency", "Studio Setup"] },
          { sessionNumber: "05", title: "Veo 3 배경 생성 & 씬 통일성", tag: "Veo 3", items: ["Veo 3 시네마틱 배경 생성 & 씬 간 조명/색감 통일", "배경과 캐릭터의 자연스러운 합성(Compositing)"], tools: ["Veo 3", "Background Sync", "Lighting", "Compositing"] },
          { sessionNumber: "06", title: "Seedance 2.0 모션 제어", tag: "Seedance 2.0", items: ["Seedance 2.0을 활용한 생생한 카메라 & 인물 움직임 제어", "렌더링 품질 최적화 및 모션 보정"], tools: ["Seedance 2.0", "Motion Control", "Animation"] },
          { sessionNumber: "07", title: "실습 1 — 숏폼 플랫폼 및 상업 영상 (과제 #1)", tag: "실습 1", items: ["숏폼 플랫폼 또는 상업 영상용 완성형 장면 제작", "강사진 피드백 및 1:1 클리닉"], tools: ["Short-form", "Coco Drama", "Commercial", "실습 #1"] },
        ],
      },
      {
        phaseNumber: "03",
        phaseTitle: "편집, 사운드 & 애니메이션",
        sessions: [
          { sessionNumber: "08", title: "Veo 3 & Seedance 2.0 하이브리드 편집", tag: "편집", items: ["다중 AI 클립 통합 편집 파이프라인", "장면 전환 및 영화적 템포 조절"], tools: ["Veo 3", "Seedance 2.0", "Edit Pipeline"] },
          { sessionNumber: "09", title: "프로 사운드: Voice AI, 음악 & SFX", tag: "사운드", items: ["일관된 AI 보이스오버, 맞춤형 배경음악(OST) 및 환경 효과음(Foley/SFX) 다층 믹싱"], tools: ["Voice AI", "Music AI", "SFX", "Audio Mix"] },
          { sessionNumber: "10", title: "실습 2 — 사운드 완성형 숏폼·상업 영상 (과제 #2)", tag: "실습 2", items: ["사운드가 완비된 고화질 숏폼 또는 상업 영상 제작 및 멘토링"], tools: ["Short-form", "Coco Drama", "Commercial", "실습 #2"] },
          { sessionNumber: "11", title: "스토리 애니메이션 & Veo 3 스타일 트랜스퍼", tag: "스타일", items: ["스토리 애니메이션 파이프라인 및 Veo 3 창의적 스타일 변환", "과제 2 피드백 반영 및 씬 디테일 보정"], tools: ["Style Transfer", "Veo 3", "Review"] },
        ],
      },
      {
        phaseNumber: "04",
        phaseTitle: "후반 작업 & 최종 마스터링",
        sessions: [
          { sessionNumber: "12", title: "전문 후반 작업: 색보정 & 4K 마스터링", tag: "후반작업", items: ["시네마틱 컬러 그레이딩, 4K 업스케일링 및 플랫폼별(YouTube, CapCut, DCP) 최적 포맷 출력"], tools: ["Color Grading", "DaVinci", "Export"] },
          { sessionNumber: "13", title: "스토리 완성작 리뷰 & 최종 폴리싱", tag: "리뷰", items: ["전체 씬 정밀 색보정, 사운드 밸런스 및 하이라이트 연출"], tools: ["Color Grade", "Story Edit", "Polishing"] },
          { sessionNumber: "14", title: "졸업 작품 완성 & 배급 준비", tag: "완성", items: ["숏폼 플랫폼 또는 상업 프로젝트용 최종 렌더링 및 Coco Drama 배급 준비"], tools: ["Final Export", "Release Ready"] },
          { sessionNumber: "15", title: "최종 세션 — 시사회, 수료증 수여 & 진로 연계", tag: "졸업", items: ["졸업 작품 시사회 & 우수작 시상", "15회차 수료증 수여 및 Coco Drama / Triệu Hỷ Media 제작팀 채용 연계"], tools: ["시사회", "수료증", "채용 연계"] },
        ],
      },
    ],
    careerOutcomesTitle: "수료 후 진로 및 협업 기회",
    careerOutcomesSubtitle: "VULEE × TRIỆU HỶ | COCO DRAMA — 나만의 작품으로 실질적인 수익 창출",
    careerOptions: [
      { direction: "방향 A", model: "독립 크리에이터", desc: "자체 제작 영화(90분 / 45화)를 Coco Drama 플랫폼에 판권 판매 또는 공식 배급 파트너십 체결.", income: "1,000만 ~ 1,500만 VND / 편" },
      { direction: "방향 B", model: "공식 제작 파트너 (CTV)", desc: "Triệu Hỷ Media 및 Vu Lee의 브리프와 시나리오에 따라 4분 분량 source를 제작하며, Coco가 credit을 지원합니다.", income: "4분 source당 500,000 VND + Coco credit 지원" },
      { direction: "방향 C", model: "제작 인력 협업", desc: "역량과 CTV·파트타임·풀타임 협업 방식에 따라 Triệu Hỷ Media 및 Vu Lee 팀과 함께합니다.", income: "월 500만 ~ 2,000만 VND" },
    ],
    filmGenres: {
      promo: ["다낭·호이안", "베트남 문화", "관광", "사랑·우정", "무술·민족정신", "숏폼 플랫폼"],
      modern: ["로맨스", "CEO·재벌", "도시 드라마", "복수극", "환생·빙의", "추리·수사", "SF·판타지"],
      commercial: ["TVC", "기업/제품 홍보", "카페/호텔/스파", "리뷰 & 가이드 영상"],
    },
    cocoPhilosophy: "기준을 충족한 수강생은 수강료 50% 지원, 실제 프로젝트 참여, Coco Drama 플랫폼 발행 및 CTV·파트타임·풀타임 협업 기회를 얻을 수 있습니다.",
    audienceTitle: "참가 대상",
    audience: ["콘텐츠 크리에이터 (YouTuber, TikToker)", "영화 감독, 시나리오 작가, 독립 영상 제작자", "마케터, 광고 기획자", "상업 단편 영상 제작 및 제작팀 취업을 희망하는 누구나"],
    venueTitle: "교육 장소 & 문의처",
    venues: [
      { name: "Hỷ Garden (Workspace & Studio)", address: "15 Trung Lương 16, Hòa Xuân, Cẩm Lệ, Đà Nẵng" },
    ],
    hotline: "0961 499 943",
  },
  contactPage: { eyebrow: "문의", title: "명확한 대화를 시작하세요", intro: "광고와 커뮤니케이션 서비스, CocoDrama, Hỷ Garden 커피 워크스페이스 또는 회사 공식 정보에 관해 TRIEU HY MEDIA로 문의해 주세요.", details: "회사 연락처", map: "Google 지도에서 주소 열기", formTitle: "문의 보내기", formIntro: "아래 양식을 작성해 주세요. 이메일 발송 서비스가 설정되지 않은 경우 직접 이메일을 보낼 수 있는 방법을 안내합니다.", fields: { name: "이름", company: "회사", email: "이메일", phone: "전화", subject: "제목", message: "메시지", consent: "TRIEU HY MEDIA가 문의에 답변하기 위해 이 정보를 사용하는 데 동의합니다.", submit: "문의 보내기", sending: "보내는 중…" } },
  privacy: { title: "개인정보 처리방침", intro: `본 개인정보 처리방침은 ${company.legalNameEn}가 공식 웹사이트를 통해 제출된 정보를 처리하는 방식을 설명합니다.`, sections: [["수집 정보", "문의 양식을 통해 자발적으로 제공하는 이름, 회사, 이메일, 전화번호, 제목 및 메시지를 수집할 수 있습니다."], ["수집 목적", "문의 응답, 비즈니스 커뮤니케이션 요구 파악, 관련 연락 유지 및 웹사이트 보호를 위해 사용합니다."], ["보관 기간", "문의 정보는 커뮤니케이션, 기록 보관 및 적법한 회사 운영에 필요한 합리적인 기간 동안만 보관합니다."], ["외부 서비스", "호스팅 및 이메일 제공업체는 서비스를 제공하는 데 필요한 범위에서 제한된 기술 또는 양식 정보를 처리할 수 있습니다."], ["정보 보호", "제출된 정보를 보호하기 위해 합리적인 관리·기술적 조치를 취하지만, 인터넷 전송이나 저장 방법의 절대적 보안은 보장할 수 없습니다."], ["이용자 권리", "적용되는 의무와 합리적인 본인 확인 절차에 따라 개인정보의 열람, 정정 또는 삭제를 요청할 수 있습니다."] ] },
  terms: { title: "이용약관", intro: "본 이용약관은 TRIEU HY MEDIA 공식 웹사이트의 방문 및 이용에 적용됩니다.", sections: [["약관 동의", "웹사이트를 이용하면 본 약관에 동의한 것으로 간주됩니다. 동의하지 않으면 이용을 중단해 주세요."], ["허용된 이용", "합법적인 정보 확인과 비즈니스 커뮤니케이션 목적으로 웹사이트를 이용할 수 있으며, 운영·보안·가용성을 방해해서는 안 됩니다."], ["회사 정보", `본 웹사이트는 ${company.legalNameEn}의 공식 정보를 투명성 및 일반 참고 목적으로 제공합니다.`], ["지식재산권", "별도 안내가 없는 한 웹사이트의 텍스트, 레이아웃, 그래픽 및 기타 원본 자료는 TRIEU HY MEDIA에 귀속되거나 사용 허가를 받은 것입니다."], ["외부 링크", "외부 사이트 링크는 편의를 위해 제공되며, 당사는 해당 콘텐츠, 보안 또는 가용성을 통제하거나 보증하지 않습니다."], ["약관 변경", "웹사이트 또는 서비스 변경에 따라 약관을 업데이트할 수 있으며, 업데이트된 약관은 게시 시점부터 적용됩니다."] ] },
} as const;

const zhContent = {
  ...shared.zh,
  home: {
    eyebrow: "企业官方网站",
    headline: "以清晰思路打造创意广告",
    intro: `${company.legalNameEn} 是一家位于越南岘港、依法注册的广告公司。我们通过清晰的传播策略、创意内容与务实的广告解决方案，为企业提供支持。`,
    explore: "探索我们的服务",
    overviewTitle: "了解 TRIEU HY MEDIA",
    overview: `${company.legalNameEn} 于 ${company.registrationDateEn} 注册成立，总部位于越南岘港市和春坊。公司专注广告业务，坚持清晰、负责与专业的服务方式。`,
    overviewDetail: "我们的工作环境融合公司办公室、Hỷ Garden 咖啡工作空间，以及 CocoDrama 等数字产品的开发。这一环境支持专注工作、创意交流与务实执行。",
    overviewImage: "TRIEU HY MEDIA 办公空间",
    learnMore: "了解更多",
    hyGarden: {
      eyebrow: "我们的工作环境",
      title: "Hỷ Garden — 办公室与咖啡空间",
      description: "Hỷ Garden 将 TRIEU HY MEDIA 的办公室和咖啡店融于同一空间。这里服务于公司的日常工作，也提供适合专注工作、团队交流和咖啡会谈的区域。",
      note: "一个让工作、沟通和日常连接自然发生的实用空间。",
      cta: "探索 Hỷ Garden",
      labels: ["TRIEU HY MEDIA 办公室", "咖啡工作空间", "花园环境", "楼上工作空间"],
    },
    cocodrama: {
      eyebrow: "数字产品",
      title: "CocoDrama 将本地化短剧带到四个东南亚市场",
      description: "正版影视内容、五种本地化语言，以及通过订阅或广告解锁剧集的灵活观看方式。",
      cta: "探索 CocoDrama",
    },
    servicesTitle: "广告与传播服务",
    servicesIntro: "为需要清晰方向、一致沟通与务实创意执行的企业提供聚焦支持。",
    approachTitle: "我们的工作方式",
    approach: [
      ["了解", "从倾听企业背景、目标与传播需求开始。"],
      ["规划", "明确务实的方向、优先事项和工作范围。"],
      ["创作", "根据共识方向开发传播内容与素材。"],
      ["交付", "谨慎协调交付，并清晰同步进度。"],
      ["复盘", "评估成果并收集反馈，进行适当优化。"],
    ],
    principlesTitle: "工作原则",
    principles: ["清晰", "责任", "一致", "创意", "专业"],
    companyTitle: "企业信息",
    ctaTitle: "让传播更清晰",
    ctaText: "欢迎联系 TRIEU HY MEDIA，咨询广告与企业传播需求。",
    cta: "联系我们的团队",
  },
  about: {
    eyebrow: "关于公司",
    title: "以清晰与责任开展企业传播",
    intro: `${company.legalNameEn} 是一家依法注册、总部位于越南岘港市的越南企业。公司于 ${company.registrationDateEn} 注册，企业编号为 ${company.businessId}。`,
    sections: [
      ["合法设立", "公司为非国有有限责任公司，当前处于正常经营状态，注册地址位于越南岘港市和春坊。"],
      ["主营业务", "公司的注册主营业务是广告，为企业提供务实的广告与传播支持。"],
      ["使命", "通过务实的广告与传播解决方案，帮助企业专业地表达其信息。"],
      ["工作原则", "我们以清晰、责任、一致性并尊重客户目标的方式开展每一个传播项目。"],
    ],
    companyTitle: "官方企业信息",
    contactTitle: "联系信息",
  },
  servicesPage: {
    eyebrow: "我们的服务",
    title: "服务与运营领域",
    intro: "TRIEU HY MEDIA 融合广告与传播支持、CocoDrama 数字产品以及 Hỷ Garden 咖啡工作空间的运营。",
    scope: "支持范围",
    process: "基本流程",
    discuss: "讨论您的项目",
    visualTitle: "从传播服务到数字产品与共享空间",
    visualLabels: ["创意策划与方向", "通过 CocoDrama 传播数字产品"],
  },
  workshopPage: {
    eyebrow: "实战特训营",
    collaboration: "TRIỆU HỶ MEDIA × VŨ LEE | COCO DRAMA",
    title: "AI SHORT DRAMA MAKER",
    courseSubtitle: "AI 影视全流程制作实战营",
    headline: "AI 影视全流程制作实战营 — 携手导演 Vũ Lee 与 Triệu Hỷ Media 展开 15 节深度特训",
    welcome: "欢迎参加 AI Short Drama Maker 专业影视实战营！",
    description: "全面掌握电影工业级 AI 短剧与动画流程：AI 剧本生成、影视叙事、动态分镜、角色与场景搭建、动态控制、剪辑合成、AI 配音、配乐音效及专业调色。",
    tuition: {
      title: "学费标准与 Coco Drama 奖学金",
      badge: "2026 特训招生",
      originalPrice: "12,000,000 越南盾/期",
      originalPriceLabel: "标准学费",
      discountPrice: "7,000,000 越南盾/期",
      discountPriceLabel: "开营早鸟特惠",
      scholarshipTitle: "Coco Drama Scholarship 奖学金计划",
      scholarshipSupport: "700万 越南盾学费资助",
      scholarshipNote: "Coco Drama Scholarship 奖学金项目为早期报名并致力于短剧创作的学员提供直接学费扶持，并提供 AI 算力额度支持与 Coco Drama 商业短剧签约制作机会。",
      duration: "15 节实战课程",
      durationLabel: "课程课时",
      location: "Hỷ Garden - 岘港市锦丽区和春坊 Trung Lương 16 街 15 号",
      locationLabel: "上课地点",
      outcomesTitle: "毕业四大核心权益与产出",
      outcomes: [
        "独立完成 1 部达到商业发行标准的完整 AI 影视成片",
        "建立属于自己的工业级 AI 电影专业作品集 (Portfolio)",
        "获得由 Triệu Hỷ Media 与 Vũ Lee 联合颁发的结业认证证书",
        "获得直接参与 Coco Drama 平台商业短剧制作项目的核心机会",
      ],
      cta: "申请早鸟特惠与奖学金",
    },
    instructors: [
      {
        name: "VU LEE",
        title: "主讲人 · AI 电影导演",
        image: "/workshop/vulee-speaker.jpg",
        bio: "将 GenAI、Veo 3、Seedance 2.0 及电影级工业管线引入商业影视与动画短剧制作的领军专家。",
      },
      {
        name: "HOÀ NGUYỄN",
        title: "特邀嘉宾 · AI 创作者 · Hulk Nón Lá 频道主理人",
        image: "/workshop/workshop-attendees.jpg",
        bio: "知名 AI 内容创作者，主理拥有百万播放量的 Hulk Nón Lá 频道，深谙视觉叙事与爆款 AI 视频实战制作。",
      },
    ],
    stats: [
      { value: "15", label: "实战课程课时" },
      { value: "04", label: "核心进阶阶段" },
      { value: "03", label: "大型实战项目" },
      { value: "成果", label: "达到要求的学员可获得合作机会" },
    ],
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdv3mJYRhMJVEKBOkpKrsDyB2xFT0VtI72YIRdY5zV5i_duGA/viewform?usp=send_form",
    ctaRegister: "立即报名参加",
    openInNewTab: "在新标签页中打开报名表",
    scanQr: "手机扫码快速报名",
    curriculumTitle: "15 节课程实战路线图",
    phases: [
      {
        phaseNumber: "01",
        phaseTitle: "构思破局 & 剧本分镜制作",
        sessions: [
          { sessionNumber: "01", title: "行业前景 & 工具链准备", tag: "行业导向", items: ["AI 影视制作行业定位与职业规划", "全套 AI 工具链详解及账户配置", "构建辅助应用提升视频制作效率", "期末课题发布：短剧平台作品或商业视频"], tools: ["Gemini", "ChatGPT", "Claude", "Build App"] },
          { sessionNumber: "02", title: "AI 剧本生成标准化流程", tag: "剧本制作", items: ["影视标准剧本结构搭建", "多模型（Gemini、ChatGPT、Claude）提示词深度调优", "AI 生成内容综合与影视化改编"], tools: ["Gemini", "ChatGPT", "Claude", "Scriptwriting"] },
          { sessionNumber: "03", title: "AI 动态分镜与专业机位拆解", tag: "分镜头", items: ["利用 AI 生成剧本分镜 & 机位/光影/运镜分析", "建立详尽 Shot List 与场景拆解", "制作周期规划与渲染工时预估", "实战：将 1 个剧本片段转化为完整分镜"], tools: ["Storyboard AI", "Shot List", "机位控制", "Pre-production"] },
        ],
      },
      {
        phaseNumber: "02",
        phaseTitle: "角色一致性 & 场景搭建",
        sessions: [
          { sessionNumber: "04", title: "角色生成、多角度一致性与工作室搭建", tag: "角色设计", items: ["高清角色设计与丰富微表情控制", "跨镜头角色面部与服装高度一致性技术", "项目角色资产库管理与工作室规范化搭建"], tools: ["Character Design", "一致性", "Studio Setup"] },
          { sessionNumber: "05", title: "Veo 3 场景构建与画面连续性", tag: "Veo 3", items: ["使用 Veo 3 构建电影级场景", "镜头间光影、色调与空间连贯性技术", "角色与环境自然融合合成"], tools: ["Veo 3", "Background Sync", "光影控制", "Compositing"] },
          { sessionNumber: "06", title: "Seedance 2.0 动态与运镜控制", tag: "Seedance 2.0", items: ["掌握 Seedance 2.0 运镜与人物肢体动作控制", "渲染画质优化与动态平滑调教"], tools: ["Seedance 2.0", "Motion Control", "Animation"] },
          { sessionNumber: "07", title: "实战演练 1 — 短剧平台与商业视频（大作业 #1）", tag: "实战 1", items: ["为短剧平台或商业视频制作完整片段", "导师 1 对 1 针对性评测与修改指导"], tools: ["Short-form", "Coco Drama", "商业视频", "实战 #1"] },
        ],
      },
      {
        phaseNumber: "03",
        phaseTitle: "剪辑合成、声音设计与动画制作",
        sessions: [
          { sessionNumber: "08", title: "Veo 3 与 Seedance 2.0 混合剪辑流程", tag: "剪辑合成", items: ["跨 AI 工具多素材无缝混剪工作流", "镜头拼接、转场与影视节奏控制"], tools: ["Veo 3", "Seedance 2.0", "Edit Pipeline"] },
          { sessionNumber: "09", title: "专业声音工程：Voice AI、配乐与音效", tag: "声音设计", items: ["全剧统一的情感配音生成", "专属电影配乐与 Foley 环境音效分层混音"], tools: ["Voice AI", "Music AI", "SFX", "Audio Mix"] },
          { sessionNumber: "10", title: "实战演练 2 — 完整有声短片制作（大作业 #2）", tag: "实战 2", items: ["制作具备完整音画的高质量短片并接受导师评审"], tools: ["CapCut", "历史短剧", "实战 #2"] },
          { sessionNumber: "11", title: "故事动画与 Veo 3 风格迁移", tag: "风格迁移", items: ["故事动画流程与 Veo 3 艺术风格迁移", "吸收作业 2 反馈并进行成片优化"], tools: ["Style Transfer", "Veo 3", "Review"] },
        ],
      },
      {
        phaseNumber: "04",
        phaseTitle: "后期母带调色与成片交付",
        sessions: [
          { sessionNumber: "12", title: "专业后期：电影调色与多端导出", tag: "后期调色", items: ["电影级 Color Grading 调色、4K 超清修复及平台定制格式导出"], tools: ["Color Grading", "DaVinci", "Export"] },
          { sessionNumber: "13", title: "作品评审与精修打磨", tag: "作品精修", items: ["逐帧画面优化、光影色彩再校准与高品质渲染导出"], tools: ["Color Grade", "Story Edit", "打磨"] },
          { sessionNumber: "14", title: "毕业作品最终交付 — 发行与商业项目就绪", tag: "成片交付", items: ["完成最终音频与调色，成片可在 Coco Drama 发布或用于商业项目"], tools: ["Final Export", "发行就绪"] },
          { sessionNumber: "15", title: "最终结营 — 作品展映、颁发证书与就业对接", tag: "结营典礼", items: ["学员毕业作品公开放映与优秀作品评选", "颁发 15 课时结业证书，直接对接 Coco Drama / Triệu Hỷ Media 创作团队合作"], tools: ["展映", "证书", "就业合作"] },
        ],
      },
    ],
    careerOutcomesTitle: "毕业出路与商业变现机会",
    careerOutcomesSubtitle: "VULEE × TRIỆU HỶ | COCO DRAMA — 靠作品实现切实商业变现",
    careerOptions: [
      { direction: "方向 A", model: "独立创作者 (Creator)", desc: "自选主题创作短剧（约90分钟/45集），Coco Drama 官方直接采购或联合发行。", income: "1000万 – 1500万 越盾 / 部" },
      { direction: "方向 B", model: "签约创作者 (CTV)", desc: "按 Vu Lee / Triệu Hỷ 的 brief 与剧本制作 4 分钟 source，Coco 提供 credit 支持。", income: "500,000 越盾 / 4 分钟 source + Coco credit 支持" },
      { direction: "方向 C", model: "制作团队合作", desc: "按能力及 CTV、兼职或全职合作方式，加入 Triệu Hỷ Media 与 Vu Lee 团队。", income: "500万 – 2000万 越盾 / 月" },
    ],
    filmGenres: {
      promo: ["岘港·会安", "历史", "越南文化", "文旅宣传", "爱情与友情", "武术精神"],
      modern: ["现代言情", "霸道总裁", "都市逆袭", "爽剧复仇", "重生逆转", "悬疑破案", "科幻与奇幻"],
      commercial: ["TVC 商业广告", "企业与产品宣传片", "餐厅/酒店/SPA 定制视频", "评测与教学视频"],
    },
    cocoPhilosophy: "达到要求的学员有机会获得 50% 学费资助、参与真实项目、在 Coco Drama 发布作品，并以 CTV、兼职或全职方式合作。",
    audienceTitle: "面向人群",
    audience: ["自媒体与内容创作者 (YouTuber, TikToker)", "独立导演、编剧与影视从业者", "广告与营销策划人员", "希望制作商业短片或加入专业 AI 影视制作团队的学习者"],
    venueTitle: "培训地点与联系方式",
    venues: [
      { name: "Hỷ Garden (创作空间与工作室)", address: "岘港市锦丽郡和春坊 Trung Lương 16 街 15 号" },
    ],
    hotline: "0961 499 943",
  },
  contactPage: {
    eyebrow: "联系我们",
    title: "开启一次清晰的沟通",
    intro: "欢迎就广告与传播服务、CocoDrama、Hỷ Garden 咖啡工作空间或企业官方信息联系 TRIEU HY MEDIA。",
    details: "企业联系信息",
    map: "在 Google 地图中打开地址",
    formTitle: "发送咨询",
    formIntro: "请填写以下表单。若邮件服务尚未配置，我们会提供直接发送邮件的选项，不会显示虚假的成功提示。",
    fields: { name: "姓名", company: "公司", email: "电子邮箱", phone: "电话", subject: "主题", message: "留言内容", consent: "我同意 TRIEU HY MEDIA 使用这些信息回复我的咨询。", submit: "发送咨询", sending: "正在发送…" },
  },
  privacy: {
    title: "隐私政策",
    intro: `本隐私政策说明 ${company.legalNameEn} 如何处理通过官方网站提交的信息。`,
    sections: [
      ["我们收集的信息", "我们可能收集您通过联系表单自愿提供的信息，包括姓名、公司、电子邮箱、电话号码、主题和留言。"],
      ["信息收集目的", "这些信息用于回复咨询、了解业务传播需求、维持相关沟通，并保护网站免受滥用。"],
      ["业务沟通", "我们仅会就您的咨询或正在进行的业务讨论，使用您提供的联系方式与您沟通。"],
      ["数据保留", "咨询信息仅会在沟通、记录保存和合法企业管理所合理需要的期间内保留。"],
      ["Cookie 与分析", "网站目前不使用非必要 Cookie 或广告分析工具。为提供和保护网站，可能会处理必要的技术数据。"],
      ["第三方服务", "托管和邮件服务商可能会在提供服务所需范围内处理有限的技术或表单信息，并适用其自身隐私条款。"],
      ["数据保护", "我们采取合理的管理和技术措施保护已提交的信息；任何互联网传输或存储方式都无法保证绝对安全。"],
      ["您的权利", "在适用义务和合理验证的前提下，您可请求访问、更正或删除已提交的个人信息。"],
      ["外部链接", "本网站链接的外部网站受其自身隐私惯例约束，我们不对其内容或政策负责。"],
      ["政策变更", "我们可能因网站或信息处理方式变更而更新本政策，更新内容发布时将同步更新生效日期。"],
    ],
  },
  terms: {
    title: "使用条款",
    intro: "本使用条款适用于访问和使用 TRIEU HY MEDIA 官方网站。",
    sections: [
      ["接受条款", "使用本网站即表示您同意这些条款；如不同意，请停止使用本网站。"],
      ["允许使用", "您可以将本网站用于合法的信息查询和业务沟通，不得干扰网站的运营、安全或可用性。"],
      ["企业信息", `本网站展示 ${company.legalNameEn} 的官方信息，用于透明披露和一般参考。`],
      ["知识产权", "除非另有说明，网站的文字、版式、图形及其他原创材料均归 TRIEU HY MEDIA 所有或获授权使用；复制或商业再利用须经许可。"],
      ["信息准确性", "我们致力于保持网站信息准确和更新。服务描述仅为一般性说明，不构成有约束力的要约、保证或专业建议。"],
      ["外部链接", "外部网站链接仅为便利提供，我们不控制或认可其内容、安全性或可用性。"],
      ["网站可用性", "在合理必要时，我们可能维护、更新或暂时暂停网站部分内容；不保证持续、不中断的可用性。"],
      ["责任限制", "在合理允许的范围内，TRIEU HY MEDIA 不对仅因依赖一般网站内容或临时不可用而产生的间接损失负责。"],
      ["条款变更", "当网站或服务发生变化时，我们可能更新本条款；更新条款发布后即生效。"],
    ],
  },
} as const;

export const content = {
  en: {
    ...shared.en,
    home: {
      eyebrow: "Official company website",
      headline: "Creative advertising built with clarity",
      intro: `${company.legalNameEn} is a legally registered advertising company based in Da Nang, Vietnam. We support businesses through thoughtful communication, creative content and practical advertising solutions.`,
      explore: "Explore our services",
      overviewTitle: "About TRIEU HY MEDIA",
      overview: `${company.legalNameEn} was registered on ${company.registrationDateEn} and is headquartered in Hoa Xuan Ward, Da Nang City, Vietnam. The company operates in the advertising sector with a commitment to clarity, responsibility and professional service delivery.`,
      overviewDetail: "Our working environment brings together the company office, Hy Garden coffee workspace and the development of digital products such as CocoDrama. This setting supports focused work, creative discussion and practical delivery.",
      overviewImage: "The working office of TRIEU HY MEDIA",
      learnMore: "Learn more about us",
      hyGarden: {
        eyebrow: "Our working environment",
        title: "Hy Garden — office and coffee shop",
        description: "Hy Garden brings together the working office of TRIEU HY MEDIA and a coffee shop within one shared setting. The space supports the company’s daily work while providing areas for focused working sessions, team conversations and time over coffee.",
        note: "A practical environment where work, communication and everyday connection can happen naturally.",
        cta: "Explore Hy Garden",
        labels: ["TRIEU HY MEDIA office", "Coffee workspace", "Garden setting", "Upstairs workspace"],
      },
      cocodrama: {
        eyebrow: "Digital product",
        title: "CocoDrama brings localized short-form stories to four Southeast Asian markets",
        description: "Licensed film content, five localization languages and flexible access through subscriptions or advertising-supported episode unlocks.",
        cta: "Explore CocoDrama",
      },
      servicesTitle: "Advertising and communication services",
      servicesIntro: "Focused support for businesses that need clear direction, consistent communication and practical creative execution.",
      approachTitle: "How we work",
      approach: [
        ["Understand", "We begin by listening to the business context, objectives and communication requirements."],
        ["Plan", "We define a practical direction, priorities and a clear scope of work."],
        ["Create", "We develop communication content and materials aligned with the agreed direction."],
        ["Deliver", "We coordinate delivery carefully and communicate progress clearly."],
        ["Review", "We review outcomes and gather feedback for appropriate refinements."],
      ],
      principlesTitle: "Working principles",
      principles: ["Clarity", "Responsibility", "Consistency", "Creativity", "Professionalism"],
      companyTitle: "Company Information",
      ctaTitle: "Let’s create clearer communication",
      ctaText: "Contact TRIEU HY MEDIA for advertising and business communication inquiries.",
      cta: "Contact our team",
    },
    about: {
      eyebrow: "About the company",
      title: "A clear, responsible approach to business communication",
      intro: `${company.legalNameEn} is a legally registered Vietnamese company headquartered in Da Nang City. The company was registered on ${company.registrationDateEn} under Business ID ${company.businessId}.`,
      sections: [
        ["Legal establishment", "The company operates as a non-state limited liability company with active status. Its registered office is located in Hoa Xuan Ward, Da Nang City, Vietnam."],
        ["Main business activity", "The company’s primary registered business activity is Advertising. Our services focus on practical advertising and communication support for businesses."],
        ["Mission", "Our goal is to support businesses in presenting their messages professionally through practical advertising and communication solutions."],
        ["Working principles", "We approach every communication project with clarity, responsibility, consistency and respect for the client’s objectives."],
      ],
      companyTitle: "Official company information",
      contactTitle: "Contact details",
    },
      servicesPage: {
      eyebrow: "Our services",
      title: "Services and operating areas",
      intro: "TRIEU HY MEDIA brings together advertising and communication support, the CocoDrama digital product, and Hy Garden coffee workspace operations.",
      scope: "Scope of support",
      process: "Basic process",
      discuss: "Discuss your project",
      visualTitle: "From communication work to digital products and shared spaces",
      visualLabels: ["Creative planning and direction", "Digital product communication through CocoDrama"],
    },
    workshopPage: {
      eyebrow: "Hands-on Masterclass",
      collaboration: "TRIEU HY MEDIA × VU LEE | COCO DRAMA",
      title: "AI SHORT DRAMA MAKER",
      courseSubtitle: "AI Film Production Masterclass",
      headline: "AI Film Production Masterclass — 15 hands-on studio sessions with Director Vu Lee & Trieu Hy Media",
      welcome: "Welcome to AI Short Drama Maker Masterclass!",
      description: "Master the complete studio-grade AI filmmaking pipeline: AI scriptwriting, storytelling, storyboarding, consistent character & scene creation, motion control, editing, Voice AI, music, SFX and color grading.",
      tuition: {
        title: "Tuition & Coco Drama Scholarship",
        badge: "Admissions 2026",
        originalPrice: "12,000,000 VND/course",
        originalPriceLabel: "Standard Tuition",
        discountPrice: "7,000,000 VND/course",
        discountPriceLabel: "Early-Bird Promotion",
        scholarshipTitle: "Coco Drama Scholarship",
        scholarshipSupport: "7 Million VND Scholarship Support",
        scholarshipNote: "The Coco Drama Scholarship program offers tuition assistance for early applicants committed to film production, with AI credits and direct commercial production access on Coco Drama.",
        duration: "15 hands-on sessions",
        durationLabel: "Duration",
        location: "Hy Garden - 15 Trung Luong 16, Hoa Xuan, Cam Le, Da Nang City",
        locationLabel: "Venue",
        outcomesTitle: "Post-Course Deliverables & Career Outcomes",
        outcomes: [
          "Complete 01 full-fledged AI film ready for release",
          "Build a professional studio-grade AI cinematic portfolio",
          "Certificate of Completion from Trieu Hy Media × Vu Lee",
          "Direct opportunity to participate in commercial Short Drama projects on Coco Drama",
        ],
        cta: "Apply for Scholarship & Early-Bird",
      },
      instructors: [
        {
          name: "VU LEE",
          title: "Speaker · AI Film Director",
          image: "/workshop/vulee-speaker.jpg",
          bio: "Pioneering expert applying GenAI, Veo 3, Seedance 2.0, and cinematic pipelines to commercial film and animated short drama production.",
        },
        {
          name: "HOÀ NGUYỄN",
          title: "Guest · AI Creator · Founder of Hulk Nón Lá",
          image: "/workshop/workshop-attendees.jpg",
          bio: "Prominent AI content creator and founder of the multi-million-view channel Hulk Nón Lá, specializing in visual storytelling and viral AI video production.",
        },
      ],
      stats: [
        { value: "15", label: "Hands-on Sessions" },
        { value: "04", label: "Core Phases" },
        { value: "03", label: "Major Projects" },
        { value: "OUTCOMES", label: "Collaboration opportunities for qualifying learners" },
      ],
      formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdv3mJYRhMJVEKBOkpKrsDyB2xFT0VtI72YIRdY5zV5i_duGA/viewform?usp=send_form",
      ctaRegister: "Register for Masterclass",
      openInNewTab: "Open Registration Form in New Tab",
      scanQr: "Scan QR code to register on mobile",
      curriculumTitle: "15-Session Curriculum Roadmap",
      phases: [
        {
          phaseNumber: "01",
          phaseTitle: "Kickoff & AI Scriptwriting",
          sessions: [
            { sessionNumber: "01", title: "Career Path & Toolkit Setup", tag: "Orientation", items: ["Career opportunities in AI cinema", "Complete AI software ecosystem setup", "Custom productivity web applications", "Graduation brief: short-form platform content or a commercial video"], tools: ["Gemini", "ChatGPT", "Claude", "Build App"] },
            { sessionNumber: "02", title: "AI Scriptwriting Pipeline", tag: "Script", items: ["Cinematic script structuring", "Prompt engineering across Gemini, ChatGPT & Claude", "Multi-model synthesis and screenwriting"], tools: ["Gemini", "ChatGPT", "Claude", "Scriptwriting"] },
            { sessionNumber: "03", title: "AI Storyboarding & Shot Breakdown", tag: "Storyboard", items: ["AI storyboard generation from script", "Camera angles, lighting & movement breakdown", "Production timeline & render budget", "Hands-on: Scene-to-storyboard conversion"], tools: ["Storyboard AI", "Shot List", "Camera Motion", "Pre-production"] },
          ],
        },
        {
          phaseNumber: "02",
          phaseTitle: "Character Design & Scene Creation",
          sessions: [
            { sessionNumber: "04", title: "Consistent Characters & Studio Setup", tag: "Characters", items: ["Photorealistic AI character design", "Multi-angle facial & outfit consistency", "Asset library management & pipeline setup"], tools: ["Character Design", "Consistency", "Studio Setup"] },
            { sessionNumber: "05", title: "Veo 3 Worldbuilding & Continuity", tag: "Veo 3", items: ["Cinematic background creation with Veo 3", "Cross-shot lighting and color continuity", "Seamless character-to-scene compositing"], tools: ["Veo 3", "Background Sync", "Lighting", "Compositing"] },
            { sessionNumber: "06", title: "Seedance 2.0 Motion & Animation", tag: "Seedance 2.0", items: ["Mastering dynamic motion in Seedance 2.0", "Camera velocity, character emotion & render fidelity"], tools: ["Seedance 2.0", "Motion Control", "Animation"] },
            { sessionNumber: "07", title: "Hands-on Project 1 — Short-form Platform & Commercial Video (Project #1)", tag: "Project 1", items: ["Creating a complete scene for a short-form platform or commercial video", "1-on-1 direct instructor review"], tools: ["Short-form", "Coco Drama", "Commercial", "Project #1"] },
          ],
        },
        {
          phaseNumber: "03",
          phaseTitle: "Editing, Sound Design & Animation",
          sessions: [
            { sessionNumber: "08", title: "Hybrid Editing with Veo 3 & Seedance 2.0", tag: "Editing", items: ["Multi-tool AI timeline editing pipeline", "Scene transitions, pacing and cinematic rhythm"], tools: ["Veo 3", "Seedance 2.0", "Edit Pipeline"] },
            { sessionNumber: "09", title: "Sound Engineering: Voice AI, Music & SFX", tag: "Sound Design", items: ["Consistent character voice acting", "Original royalty-free cinematic score", "Layered Foley and ambient sound FX mix"], tools: ["Voice AI", "Music AI", "SFX", "Audio Mix"] },
            { sessionNumber: "10", title: "Hands-on Project 2 — Short-form & Commercial Video with Full Audio (Project #2)", tag: "Project 2", items: ["Producing a complete short-form or commercial video with soundtrack and voiceover"], tools: ["Short-form", "Coco Drama", "Commercial", "Project #2"] },
            { sessionNumber: "11", title: "Story Animation & Veo 3 Style Transfer", tag: "Style", items: ["Story animation workflow", "Creative style transfer in Veo 3", "Iterating and optimizing project #2"], tools: ["Style Transfer", "Veo 3", "Review"] },
          ],
        },
        {
          phaseNumber: "04",
          phaseTitle: "Post-Production & Final Mastering",
          sessions: [
            { sessionNumber: "12", title: "Professional Post-Production: Color Grading & Export", tag: "Mastering", items: ["Cinematic color science, 4K AI upscaling, and platform-optimized formats (YouTube, CapCut, DCP)"], tools: ["Color Grading", "DaVinci", "Export"] },
            { sessionNumber: "13", title: "Final Polish & Story Film Review", tag: "Review", items: ["Scene-by-scene audio and color polish, final rendering"], tools: ["Color Grade", "Story Edit", "Polishing"] },
            { sessionNumber: "14", title: "Graduation Project Finalization", tag: "Graduation", items: ["Final export ready for short-form platform release or commercial delivery"], tools: ["Final Export", "Release Ready"] },
            { sessionNumber: "15", title: "Final Screening, Certification & Career Placement", tag: "Ceremony", items: ["Public screening & top project awards", "Official certification and recruitment into Coco Drama / Trieu Hy Media production units"], tools: ["Screening", "Certificate", "Recruitment"] },
          ],
        },
      ],
      careerOutcomesTitle: "Career Opportunities & Commercial Monetization",
      careerOutcomesSubtitle: "VULEE × TRIỆU HỶ | COCO DRAMA — Turn your film creations into sustainable income",
      careerOptions: [
        { direction: "TRACK A", model: "INDEPENDENT CREATOR", desc: "Create original AI short series (90 mins / ~45 eps). Coco Drama acquires or co-releases your title.", income: "10M – 15M VND / Series" },
        { direction: "TRACK B", model: "CONTRACT PRODUCER (CTV)", desc: "Produce a 4-minute source from briefs and scripts supplied by Vu Lee / Trieu Hy; Coco provides credit support.", income: "500,000 VND / 4-minute source + Coco credit support" },
        { direction: "TRACK C", model: "PRODUCTION TEAM COLLABORATOR", desc: "Collaborate with Trieu Hy Media & Vu Lee according to capability and a CTV, part-time or full-time arrangement.", income: "5M – 20M VND / Month" },
      ],
      filmGenres: {
        promo: ["Da Nang – Hoi An", "History", "Vietnamese Culture", "Tourism", "Romance & Friendship", "Martial Arts"],
        modern: ["Modern Romance", "CEO Drama", "Urban Rebirth", "Vengeance", "Crime & Mystery", "Sci-Fi & Fantasy"],
        commercial: ["TVC Commercials", "Brand & Product Films", "Café / Hotel / Spa Showcases", "Reviews & Tutorials"],
      },
      cocoPhilosophy: "Qualifying learners may receive a 50% tuition subsidy, join real projects, release films on Coco Drama, and collaborate as CTVs, part-time or full-time team members.",
      audienceTitle: "Who Should Attend",
      audience: ["Content Creators (YouTubers, TikTokers)", "Independent Filmmakers, Directors & Screenwriters", "Brand Marketers & Creative Agency Strategists", "Anyone eager to produce commercial short films with AI"],
      venueTitle: "Training Venue & Contact",
      venues: [
        { name: "Hy Garden (Workspace & Studio)", address: "15 Trung Luong 16, Hoa Xuan, Cam Le, Da Nang City" },
      ],
      hotline: "0961 499 943",
    },
    contactPage: {
      eyebrow: "Contact",
      title: "Start a clear conversation",
      intro: "Contact TRIEU HY MEDIA regarding advertising and communication support, CocoDrama, Hy Garden coffee workspace or official company inquiries.",
      details: "Company contact details",
      map: "Open address in Google Maps",
      formTitle: "Send an inquiry",
      formIntro: "Complete the form below. If email delivery is not configured, we will provide a direct email option without showing a false success message.",
      fields: { name: "Full name", company: "Company", email: "Email", phone: "Phone", subject: "Subject", message: "Message", consent: "I agree that TRIEU HY MEDIA may use this information to respond to my inquiry.", submit: "Send inquiry", sending: "Sending…" },
    },
    privacy: {
      title: "Privacy Policy",
      intro: `This Privacy Policy explains how ${company.legalNameEn} handles information submitted through this official website.`,
      sections: [
        ["Information we collect", "We may collect the information you choose to provide through the contact form, including your name, company, email address, phone number, subject and message."],
        ["Purpose of data collection", "Information is used to respond to inquiries, understand business communication needs, maintain relevant correspondence and protect the website from misuse."],
        ["Business communication", "We may contact you using the details you provide solely in relation to your inquiry or an ongoing business discussion."],
        ["Data retention", "Inquiry information is retained only for as long as reasonably necessary for communication, record-keeping and legitimate business administration."],
        ["Cookies and analytics", "This website does not currently use non-essential cookies or advertising analytics. Essential technical data may be processed to deliver and secure the website."],
        ["Third-party services", "Hosting and email delivery providers may process limited technical or form information as necessary to provide their services. Their own privacy terms apply."],
        ["Data protection", "We take reasonable administrative and technical measures to protect submitted information. No internet transmission or storage method can be guaranteed as completely secure."],
        ["Your rights", "You may ask us to access, correct or delete personal information you submitted, subject to applicable obligations and reasonable verification."],
        ["External links", "External websites linked from this site are governed by their own privacy practices. We are not responsible for their content or policies."],
        ["Changes to this policy", "We may update this policy to reflect changes to the website or our information practices. The effective date will be updated when changes are published."],
      ],
    },
    terms: {
      title: "Terms of Use",
      intro: "These Terms of Use apply to access and use of the official TRIEU HY MEDIA website.",
      sections: [
        ["Acceptance of terms", "By using this website, you agree to these terms. If you do not agree, please discontinue use of the website."],
        ["Permitted use", "You may use this website for lawful informational and business communication purposes. You must not interfere with its operation, security or availability."],
        ["Company information", `This website presents official information about ${company.legalNameEn}. Company details are provided for transparency and general information.`],
        ["Intellectual property", "Website text, layout, graphics and other original materials are owned by or licensed to TRIEU HY MEDIA unless otherwise stated. Reasonable personal and business reference use is permitted; reproduction or commercial reuse requires permission."],
        ["Accuracy of information", "We aim to keep website information accurate and current. Service descriptions are general and do not constitute a binding proposal, guarantee or professional advice."],
        ["External links", "Links to external websites are provided for convenience. We do not control or endorse their content, security or availability."],
        ["Website availability", "We may maintain, update or temporarily suspend parts of the website when reasonably necessary. Continuous, uninterrupted availability is not guaranteed."],
        ["Limitation of liability", "To the extent reasonably permitted, TRIEU HY MEDIA is not responsible for indirect loss arising solely from reliance on general website content or temporary unavailability."],
        ["Changes to these terms", "We may update these terms when the website or its services change. Updated terms take effect when published."],
      ],
    },
  },
  vi: {
    ...shared.vi,
    home: {
      eyebrow: "Website chính thức của doanh nghiệp",
      headline: "Giải pháp quảng cáo được xây dựng từ sự rõ ràng",
      intro: `${company.legalNameVi} là doanh nghiệp hoạt động trong lĩnh vực quảng cáo tại Thành phố Đà Nẵng, Việt Nam. Công ty hỗ trợ doanh nghiệp thông qua truyền thông rõ ràng, nội dung sáng tạo và các giải pháp quảng cáo thực tế.`,
      explore: "Khám phá dịch vụ",
      overviewTitle: "Giới thiệu TRIEU HY MEDIA",
      overview: `${company.legalNameVi} được đăng ký hoạt động ngày ${company.registrationDateVi} và có trụ sở tại Phường Hòa Xuân, Thành phố Đà Nẵng, Việt Nam. Công ty hoạt động trong lĩnh vực quảng cáo với định hướng rõ ràng, trách nhiệm và chuyên nghiệp.`,
      overviewDetail: "Môi trường làm việc của công ty kết hợp văn phòng, không gian coffee workspace Hỷ Garden và hoạt động phát triển sản phẩm số như CocoDrama. Không gian này hỗ trợ làm việc tập trung, trao đổi sáng tạo và triển khai công việc thực tế.",
      overviewImage: "Văn phòng làm việc của TRIEU HY MEDIA",
      learnMore: "Tìm hiểu thêm về chúng tôi",
      hyGarden: {
        eyebrow: "Không gian làm việc",
        title: "Hỷ Garden — văn phòng làm việc và coffee shop",
        description: "Hỷ Garden kết hợp văn phòng làm việc của TRIEU HY MEDIA và coffee shop trong cùng một không gian. Đây là nơi phục vụ hoạt động làm việc hằng ngày của công ty, đồng thời có các khu vực phù hợp cho làm việc tập trung, trao đổi đội ngũ và những cuộc trò chuyện bên cà phê.",
        note: "Một môi trường thực tế để công việc, giao tiếp và sự kết nối diễn ra tự nhiên.",
        cta: "Khám phá Hỷ Garden",
        labels: ["Văn phòng TRIEU HY MEDIA", "Không gian coffee workspace", "Khu sân vườn", "Không gian làm việc tầng trên"],
      },
      cocodrama: {
        eyebrow: "Sản phẩm số",
        title: "CocoDrama đưa phim ngắn được bản địa hóa đến bốn thị trường Đông Nam Á",
        description: "Nội dung phim có bản quyền, năm ngôn ngữ bản địa hóa và quyền truy cập linh hoạt qua gói dịch vụ hoặc hình thức mở tập bằng quảng cáo.",
        cta: "Khám phá CocoDrama",
      },
      servicesTitle: "Dịch vụ quảng cáo và truyền thông",
      servicesIntro: "Hỗ trợ tập trung cho doanh nghiệp cần định hướng rõ ràng, truyền thông nhất quán và triển khai sáng tạo thực tế.",
      approachTitle: "Cách chúng tôi làm việc",
      approach: [
        ["Tiếp nhận yêu cầu", "Lắng nghe bối cảnh, mục tiêu và yêu cầu truyền thông của doanh nghiệp."],
        ["Lập kế hoạch", "Xác định định hướng thực tế, thứ tự ưu tiên và phạm vi công việc rõ ràng."],
        ["Phát triển nội dung", "Xây dựng nội dung và tài liệu truyền thông theo định hướng đã thống nhất."],
        ["Triển khai", "Phối hợp bàn giao cẩn trọng và cập nhật tiến độ rõ ràng."],
        ["Đánh giá và phản hồi", "Rà soát kết quả, tiếp nhận phản hồi và hiệu chỉnh phù hợp."],
      ],
      principlesTitle: "Nguyên tắc làm việc",
      principles: ["Rõ ràng", "Trách nhiệm", "Nhất quán", "Sáng tạo", "Chuyên nghiệp"],
      companyTitle: "Thông tin doanh nghiệp",
      ctaTitle: "Cùng tạo nên truyền thông rõ ràng hơn",
      ctaText: "Liên hệ TRIEU HY MEDIA về nhu cầu quảng cáo và truyền thông doanh nghiệp.",
      cta: "Liên hệ đội ngũ",
    },
    about: {
      eyebrow: "Giới thiệu doanh nghiệp",
      title: "Tiếp cận truyền thông doanh nghiệp bằng sự rõ ràng và trách nhiệm",
      intro: `${company.legalNameVi} là doanh nghiệp Việt Nam được đăng ký hợp pháp và có trụ sở tại Thành phố Đà Nẵng. Công ty được đăng ký hoạt động ngày ${company.registrationDateVi} theo mã số doanh nghiệp ${company.businessId}.`,
      sections: [
        ["Thành lập pháp lý", "Công ty hoạt động theo loại hình công ty trách nhiệm hữu hạn ngoài nhà nước, hiện có tình trạng đang hoạt động và đặt trụ sở tại Phường Hòa Xuân, Thành phố Đà Nẵng, Việt Nam."],
        ["Ngành nghề kinh doanh chính", "Ngành nghề kinh doanh chính của công ty là Quảng cáo. Các dịch vụ tập trung vào giải pháp quảng cáo và hỗ trợ truyền thông thực tế cho doanh nghiệp."],
        ["Sứ mệnh", "Mục tiêu của công ty là hỗ trợ doanh nghiệp truyền tải thông điệp chuyên nghiệp thông qua các giải pháp quảng cáo và truyền thông thực tế."],
        ["Nguyên tắc làm việc", "Công ty tiếp cận mỗi hoạt động truyền thông dựa trên sự rõ ràng, trách nhiệm, nhất quán và tôn trọng mục tiêu của khách hàng."],
      ],
      companyTitle: "Thông tin doanh nghiệp chính thức",
      contactTitle: "Thông tin liên hệ",
    },
      servicesPage: {
      eyebrow: "Dịch vụ của chúng tôi",
      title: "Dịch vụ và mảng hoạt động",
      intro: "TRIEU HY MEDIA kết hợp dịch vụ quảng cáo và truyền thông, sản phẩm số CocoDrama cùng hoạt động coffee workspace Hỷ Garden.",
      scope: "Phạm vi hỗ trợ",
      process: "Quy trình cơ bản",
      discuss: "Trao đổi nhu cầu của bạn",
      visualTitle: "Từ truyền thông đến sản phẩm số và không gian chung",
      visualLabels: ["Lập kế hoạch và định hướng sáng tạo", "Truyền thông sản phẩm số qua CocoDrama"],
    },
    workshopPage: {
      eyebrow: "Khóa Học Thực Chiến",
      collaboration: "TRIỆU HỶ MEDIA × VŨ LEE | COCO DRAMA",
      title: "AI SHORT DRAMA MAKER",
      courseSubtitle: "Khóa học sản xuất phim bằng AI",
      headline: "Khóa học sản xuất phim bằng AI — 15 buổi thực chiến cùng Đạo diễn Vũ Lee & Triệu Hỷ Media",
      welcome: "Chào mừng bạn đến với Khóa đào tạo AI Short Drama Maker!",
      description: "Quy trình làm phim chuẩn studio từ xây dựng ý tưởng, kịch bản phân cảnh, tạo hình nhân vật nhất quán, bối cảnh Veo 3, chuyển động Seedance 2.0 đến dựng phim, âm thanh và hoàn thiện phim ngắn cho nền tảng nội dung số hoặc video thương mại.",
      tuition: {
        title: "Học Phí & Học Bổng Coco Drama",
        badge: "Tuyển sinh 2026",
        originalPrice: "12.000.000đ/khóa",
        originalPriceLabel: "Học phí gốc",
        discountPrice: "7.000.000đ/khóa",
        discountPriceLabel: "Ưu đãi khai giảng",
        scholarshipTitle: "Coco Drama Scholarship",
        scholarshipSupport: "Học bổng hỗ trợ học phí 7 triệu",
        scholarshipNote: "Chương trình Coco Drama Scholarship hỗ trợ học phí dành cho học viên đăng ký sớm và cam kết đồng hành sản xuất phim ngắn. Cơ hội được tài trợ credit AI và tham gia trực tiếp dự án Short Drama trên nền tảng Coco Drama.",
        duration: "15 buổi thực chiến",
        durationLabel: "Thời lượng",
        location: "HỶ GARDEN - 15 Trung Lương 16, P. Hòa Xuân, Q. Cẩm Lệ, TP. Đà Nẵng",
        locationLabel: "Địa điểm học",
        outcomesTitle: "Cam Kết Đầu Ra Sau Khóa Học",
        outcomes: [
          "Hoàn thiện 01 sản phẩm phim AI hoàn chỉnh sẵn sàng phát hành",
          "Sở hữu portfolio điện ảnh AI cá nhân chuẩn studio",
          "Giấy xác nhận hoàn thành khóa học từ Triệu Hỷ Media × Vũ Lee",
          "Cơ hội tham gia dự án Short Drama thương mại trên nền tảng Coco Drama",
        ],
        cta: "Đăng ký nhận học bổng & ưu đãi",
      },
      instructors: [
        {
          name: "VU LEE",
          title: "Nhà diễn giả · AI Film Director",
          image: "/workshop/vulee-speaker.jpg",
          bio: "Chuyên gia tiên phong trong việc ứng dụng công nghệ GenAI, Veo 3, Seedance 2.0 và quy trình điện ảnh vào sản xuất phim thương mại, phim hoạt hình và phim ngắn tại Việt Nam.",
        },
        {
          name: "HOÀ NGUYỄN",
          title: "Khách mời · AI Creator · Chủ kênh Hulk Nón Lá",
          image: "/workshop/workshop-attendees.jpg",
          bio: "Nhà sáng tạo nội dung AI nổi bật, chủ sở hữu kênh Hulk Nón Lá với hàng triệu lượt xem, chuyên sâu về tư duy hình ảnh, kể chuyện trực quan và sản xuất video AI viral.",
        },
      ],
      stats: [
        { value: "15", label: "Buổi học thực chiến" },
        { value: "04", label: "Giai đoạn chuyên sâu" },
        { value: "03", label: "Bài thực hành lớn" },
        { value: "ĐẦU RA", label: "Cơ hội hợp tác dành cho học viên đạt yêu cầu" },
      ],
      formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdv3mJYRhMJVEKBOkpKrsDyB2xFT0VtI72YIRdY5zV5i_duGA/viewform?usp=send_form",
      ctaRegister: "Đăng ký tham gia ngay",
      openInNewTab: "Mở form đăng ký trên tab mới",
      scanQr: "Quét mã QR để đăng ký nhanh trên điện thoại",
      curriculumTitle: "Lộ trình 15 Buổi Thực Chiến",
      phases: [
        {
          phaseNumber: "01",
          phaseTitle: "Khởi Động & Sản Xuất Kịch Bản",
          sessions: [
            {
              sessionNumber: "01",
              title: "Định Hướng Nghề Nghiệp & Chuẩn Bị Công Cụ",
              tag: "Định hướng",
              items: [
                "Định hướng nghề nghiệp trong ngành sản xuất phim AI",
                "Giới thiệu toàn bộ hệ sinh thái công cụ sẽ sử dụng trong khóa học",
                "Chuẩn bị và thiết lập các tài khoản cần thiết",
                "Ứng dụng build app phục vụ công việc và sản xuất video",
                "Giao bài cuối khóa: phim ngắn cho nền tảng nội dung số hoặc video thương mại",
              ],
              tools: ["Gemini", "ChatGPT", "Claude", "Build App"],
            },
            {
              sessionNumber: "02",
              title: "Quy Trình Sản Xuất Kịch Bản AI",
              tag: "Kịch bản",
              items: [
                "Quy trình sản xuất kịch bản bằng ứng dụng chuyên dụng & cấu trúc kịch bản chuẩn điện ảnh",
                "Tối ưu đầu ra và tinh chỉnh nội dung prompt chuyên sâu",
                "Sản xuất kịch bản với Gemini, ChatGPT và Claude cho nội dung sáng tạo",
                "So sánh và tổng hợp kết quả đa AI",
              ],
              tools: ["Gemini", "ChatGPT", "Claude", "Scriptwriting"],
            },
            {
              sessionNumber: "03",
              title: "Storyboard AI & Phân Cảnh Chuyên Nghiệp",
              tag: "Storyboard",
              items: [
                "Sử dụng AI tạo storyboard từ kịch bản viết sẵn",
                "Phân tích cảnh quay: góc máy, ánh sáng, chuyển động camera",
                "Tạo shot list và breakdown cảnh quay chi tiết",
                "Lập kế hoạch sản xuất và ước lượng thời gian render",
                "Thực hành: Chuyển đổi 1 cảnh kịch bản thành storyboard hoàn chỉnh",
              ],
              tools: ["Storyboard AI", "Shot List", "Góc Máy", "Pre-production"],
            },
          ],
        },
        {
          phaseNumber: "02",
          phaseTitle: "Tạo Nhân Vật & Dựng Bối Cảnh",
          sessions: [
            {
              sessionNumber: "04",
              title: "Tạo Nhân Vật, Đồng Bộ & Xây Dựng Studio",
              tag: "Nhân vật",
              items: [
                "Tạo nhân vật AI sắc nét với biểu cảm phong phú",
                "Kỹ thuật đồng bộ nhân vật xuyên suốt các cảnh quay",
                "Quản lý thư viện nhân vật dự án",
                "Xây dựng Studio sản xuất hoàn chỉnh và khoa học",
              ],
              tools: ["Character Design", "Đồng Bộ", "Studio Setup", "Consistency"],
            },
            {
              sessionNumber: "05",
              title: "Tạo Bối Cảnh với Veo 3 & Đồng Nhất Cảnh Quay",
              tag: "Veo 3",
              items: [
                "Tạo bối cảnh điện ảnh chuyên nghiệp bằng Veo 3",
                "Kỹ thuật đồng nhất bối cảnh xuyên cảnh quay",
                "Kết hợp nhân vật vào bối cảnh tự nhiên, liền mạch",
                "Kiểm soát ánh sáng, màu sắc và không gian",
              ],
              tools: ["Veo 3", "Background Sync", "Ánh Sáng", "Compositing"],
            },
            {
              sessionNumber: "06",
              title: "Ứng Dụng Seedance 2.0",
              tag: "Seedance 2.0",
              items: [
                "Làm chủ Seedance 2.0 trong sản xuất phim AI",
                "Kỹ thuật tạo chuyển động mượt mà và sống động",
                "Kiểm soát tốc độ, hướng chuyển động và biểu cảm",
                "Tối ưu đầu ra và kiểm soát chất lượng render",
              ],
              tools: ["Seedance 2.0", "Motion Control", "Animation", "Render"],
            },
            {
              sessionNumber: "07",
              title: "Thực Hành 1 — Phim Ngắn Nền Tảng & Video Thương Mại (Bài TH #1)",
              tag: "Thực Hành 1",
              items: [
                "Học viên chọn brief phim ngắn cho nền tảng nội dung số hoặc video thương mại",
                "Kết hợp nhân vật + bối cảnh + chuyển động thành cảnh quay hoàn chỉnh",
                "Áp dụng kỹ thuật đồng bộ nhân vật & bối cảnh đã học",
                "Nộp bài & nhận phản hồi trực tiếp từ giảng viên",
              ],
              tools: ["Short-form", "Coco Drama", "Video Thương Mại", "Thực Hành #1"],
            },
          ],
        },
        {
          phaseNumber: "03",
          phaseTitle: "Dựng Phim, Âm Thanh & Hoạt Hình",
          sessions: [
            {
              sessionNumber: "08",
              title: "Dựng Phim Kết Hợp Veo 3 & Seedance 2.0",
              tag: "Dựng phim",
              items: [
                "Quy trình dựng phim tích hợp đa công cụ AI",
                "Kết hợp cảnh từ Veo 3 và Seedance 2.0 trong một dự án",
                "Kỹ thuật ghép cảnh, chuyển cảnh mượt mà",
                "Kiểm soát nhịp điệu và tiết tấu của phim",
              ],
              tools: ["Veo 3", "Seedance 2.0", "Edit Pipeline", "Nhịp Điệu"],
            },
            {
              sessionNumber: "09",
              title: "Âm Thanh Chuyên Nghiệp: Voice AI, Music & SFX",
              tag: "Voice & SFX",
              items: [
                "Kỹ thuật tạo giọng nói (voice) đồng nhất toàn dự án",
                "Sản xuất nhạc nền phù hợp phong cách phim",
                "Thiết kế Sound Effects (SFX) chuyên nghiệp",
                "Phân lớp âm thanh: dialogue, music, ambient, SFX",
                "Xuất file âm thanh chất lượng cao cho dự án",
              ],
              tools: ["Voice AI", "Music AI", "SFX", "Audio Mix"],
            },
            {
              sessionNumber: "10",
              title: "Thực Hành 2 — Phim Ngắn Hoàn Chỉnh & Video Thương Mại (Bài TH #2)",
              tag: "Thực Hành 2",
              items: [
                "Học viên phát triển phim ngắn nền tảng hoặc video thương mại từ bài TH1",
                "Sản xuất đoạn phim ngắn hoàn chỉnh với âm thanh đầy đủ",
                "Áp dụng toàn bộ kỹ năng: kịch bản, nhân vật, bối cảnh, dựng phim",
                "Nộp bài và nhận review chi tiết từ giảng viên",
              ],
              tools: ["Short-form", "Coco Drama", "Video Thương Mại", "Thực Hành #2"],
            },
            {
              sessionNumber: "11",
              title: "Hoạt Hình Story & Style Transfer trong Veo 3",
              tag: "Story & Style",
              items: [
                "Quy trình sản xuất hoạt hình Story chuyên nghiệp",
                "Chuyển đổi styles sáng tạo trong Veo 3",
                "Tạo chuyển động ấn tượng và kiểm soát phong cách",
                "Sửa bài thực hành số 2 theo phản hồi giảng viên và tối ưu cho mục tiêu phát hành",
              ],
              tools: ["Style Transfer", "Veo 3", "Hoạt Hình Story", "Review TH #2"],
            },
          ],
        },
        {
          phaseNumber: "04",
          phaseTitle: "Thực Hành & Hoàn Thiện",
          sessions: [
            {
              sessionNumber: "12",
              title: "Hậu Kỳ Chuyên Nghiệp: Color Grading & Xuất Video",
              tag: "Hậu Kỳ",
              items: [
                "Kỹ thuật color grading điện ảnh cho video AI",
                "Hiệu chỉnh màu sắc, độ tương phản và saturation từng cảnh",
                "Xuất video chất lượng cao cho các nền tảng khác nhau",
                "Tối ưu file size và format: YouTube, Instagram, CapCut, DCP",
              ],
              tools: ["Color Grading", "DaVinci", "Export", "Post-production"],
            },
            {
              sessionNumber: "13",
              title: "Review & Hoàn Thiện Bài Thực Hành Story",
              tag: "Review Story",
              items: [
                "Review tổng thể bài hoạt hình Story từng học viên",
                "Chỉnh sửa chi tiết từng cảnh quay và chuyển cảnh",
                "Tinh chỉnh màu sắc, ánh sáng, nhịp điệu theo phản hồi",
                "Đánh bóng và xuất sản phẩm chất lượng cao",
              ],
              tools: ["Color Grade", "Story Edit", "Đánh Bóng", "Export"],
            },
            {
              sessionNumber: "14",
              title: "Hoàn Thiện Bài Tốt Nghiệp — Phát Hành & Thương Mại",
              tag: "Tốt Nghiệp",
              items: [
                "Hoàn thiện phim ngắn cho nền tảng nội dung số hoặc video thương mại",
                "Tổng hợp toàn bộ kỹ năng trong một sản phẩm hoàn chỉnh",
                "Hậu kỳ âm thanh và color grade lần cuối",
                "Xuất bản phim hoàn chỉnh, sẵn sàng phát hành trên Coco Drama hoặc cung ứng cho dự án thương mại",
              ],
              tools: ["Short-form", "Final Export", "Coco Drama", "Sẵn Sàng"],
            },
            {
              sessionNumber: "15",
              title: "Buổi Cuối — Thực Hành, Tổng Kết & Trao Chứng Chỉ",
              tag: "Tổng Kết",
              items: [
                "Học viên trình bày phim ngắn hoặc video thương mại tốt nghiệp",
                "Nhận xét tổng thể từ giảng viên và bình chọn sản phẩm xuất sắc nhất",
                "Tổng kết toàn bộ lộ trình 15 buổi & cấp chứng chỉ hoàn thành khóa học",
                "Định hướng phát triển nghề nghiệp AI Filmmaking & Tuyển dụng vào Coco Drama / Triệu Hỷ Media",
              ],
              tools: ["Trình Bày", "Chứng Chỉ", "Định Hướng Nghề Nghiệp", "Tốt Nghiệp"],
            },
          ],
        },
      ],
      careerOutcomesTitle: "Đầu Ra Sau Tốt Nghiệp & Cơ Hội Hợp Tác",
      careerOutcomesSubtitle: "VULEE × TRIỆU HỶ | COCO DRAMA — Tạo thu nhập thực tế từ chính tác phẩm của bạn",
      careerOptions: [
        {
          direction: "HƯỚNG A",
          model: "CREATOR ĐỘC LẬP",
          desc: "Tự làm phim, tự chọn chủ đề (90 phút ~ 45 tập). Coco Drama thu mua hoặc hợp tác phát hành trọn gói.",
          income: "10 – 15 triệu / Bộ phim",
        },
        {
          direction: "HƯỚNG B",
          model: "CỘNG TÁC VIÊN (CTV)",
          desc: "Vu Lee / Triệu Hỷ giao brief và kịch bản; sản xuất source phim ngắn theo yêu cầu, Coco hỗ trợ credit.",
          income: "500.000đ / source 4 phút + Coco hỗ trợ credit",
        },
        {
          direction: "HƯỚNG C",
          model: "NHÂN SỰ SẢN XUẤT",
          desc: "Hợp tác cùng đội ngũ sản xuất Triệu Hỷ Media & Vu Lee theo năng lực và hình thức CTV, Part-time hoặc Full-time.",
          income: "5 – 20 triệu / tháng",
        },
      ],
      filmGenres: {
        promo: ["Đà Nẵng – Hội An", "Văn hóa Việt Nam", "Du lịch", "Tình yêu – Tình bạn", "Võ thuật – Tinh thần dân tộc", "Phim ngắn nền tảng"],
        modern: ["Ngôn tình", "Tổng tài", "Đô thị", "Báo thù", "Trùng sinh", "Phá án", "Viễn tưởng – Fantasy"],
        commercial: ["TVC", "Video doanh nghiệp / Sản phẩm", "Không gian Café / Spa / Khách sạn", "Review & Hướng dẫn"],
      },
      cocoPhilosophy: "Học viên đạt yêu cầu có cơ hội được tài trợ 50% học phí, được tham gia dự án thật, phát hành phim trên nền tảng Coco Drama và hợp tác theo hình thức CTV – Part-time – Full-time.",
      audienceTitle: "Đối tượng tham gia",
      audience: [
        "Nhà sáng tạo nội dung (Content Creators, YouTubers, TikTokers)",
        "Đạo diễn, Biên kịch, Nhà làm phim tự do",
        "Chuyên viên Marketing, Truyền thông & Agency",
        "Người muốn tạo ra các bộ phim ngắn thương mại hoặc gia nhập đội ngũ sản xuất",
      ],
      venueTitle: "Địa điểm Đào tạo & Liên hệ",
      venues: [
        { name: "Hỷ Garden (Workspace & Studio)", address: "15 Trung Lương 16, Hòa Xuân, Cẩm Lệ, TP. Đà Nẵng" },
      ],
      hotline: "0961 499 943",
    },
    contactPage: {
      eyebrow: "Liên hệ",
      title: "Bắt đầu một cuộc trao đổi rõ ràng",
      intro: "Liên hệ TRIEU HY MEDIA về quảng cáo và truyền thông, CocoDrama, Hỷ Garden coffee workspace hoặc thông tin chính thức của doanh nghiệp.",
      details: "Thông tin liên hệ doanh nghiệp",
      map: "Mở địa chỉ trên Google Maps",
      formTitle: "Gửi yêu cầu",
      formIntro: "Hoàn thành biểu mẫu bên dưới. Nếu dịch vụ gửi email chưa được cấu hình, website sẽ cung cấp tùy chọn gửi email trực tiếp và không hiển thị thông báo thành công giả.",
      fields: { name: "Họ và tên", company: "Công ty", email: "Email", phone: "Điện thoại", subject: "Chủ đề", message: "Nội dung", consent: "Tôi đồng ý để TRIEU HY MEDIA sử dụng thông tin này nhằm phản hồi yêu cầu của tôi.", submit: "Gửi yêu cầu", sending: "Đang gửi…" },
    },
    privacy: {
      title: "Chính sách bảo mật",
      intro: `Chính sách này giải thích cách ${company.legalNameVi} xử lý thông tin được gửi qua website chính thức.`,
      sections: [
        ["Thông tin được thu thập", "Công ty có thể thu thập thông tin do bạn chủ động cung cấp qua biểu mẫu liên hệ, gồm họ tên, công ty, email, số điện thoại, chủ đề và nội dung."],
        ["Mục đích thu thập", "Thông tin được sử dụng để phản hồi yêu cầu, tìm hiểu nhu cầu truyền thông, duy trì trao đổi liên quan và bảo vệ website khỏi hành vi lạm dụng."],
        ["Liên lạc công việc", "Công ty có thể liên hệ qua thông tin bạn cung cấp chỉ trong phạm vi yêu cầu hoặc nội dung trao đổi công việc đang diễn ra."],
        ["Thời gian lưu trữ", "Thông tin yêu cầu chỉ được lưu trong thời gian hợp lý cần thiết cho việc trao đổi, lưu hồ sơ và quản trị doanh nghiệp chính đáng."],
        ["Cookie và phân tích", "Website hiện không sử dụng cookie không thiết yếu hoặc công cụ phân tích quảng cáo. Dữ liệu kỹ thuật thiết yếu có thể được xử lý để vận hành và bảo vệ website."],
        ["Dịch vụ bên thứ ba", "Nhà cung cấp dịch vụ lưu trữ và gửi email có thể xử lý một phần dữ liệu kỹ thuật hoặc dữ liệu biểu mẫu khi cần thiết để cung cấp dịch vụ. Chính sách riêng của họ sẽ được áp dụng."],
        ["Bảo vệ dữ liệu", "Công ty áp dụng các biện pháp quản trị và kỹ thuật hợp lý để bảo vệ thông tin. Không phương thức truyền hoặc lưu trữ qua internet nào có thể được bảo đảm an toàn tuyệt đối."],
        ["Quyền của người dùng", "Bạn có thể yêu cầu truy cập, sửa hoặc xóa thông tin cá nhân đã cung cấp, tùy theo nghĩa vụ áp dụng và quy trình xác minh hợp lý."],
        ["Liên kết bên ngoài", "Website bên ngoài được điều chỉnh bởi chính sách riêng của họ. Công ty không chịu trách nhiệm về nội dung hoặc chính sách của các website đó."],
        ["Thay đổi chính sách", "Chính sách có thể được cập nhật khi website hoặc cách xử lý thông tin thay đổi. Ngày hiệu lực sẽ được cập nhật khi nội dung mới được công bố."],
      ],
    },
    terms: {
      title: "Điều khoản sử dụng",
      intro: "Điều khoản này áp dụng khi truy cập và sử dụng website chính thức của TRIEU HY MEDIA.",
      sections: [
        ["Chấp nhận điều khoản", "Khi sử dụng website, bạn đồng ý với các điều khoản này. Nếu không đồng ý, vui lòng ngừng sử dụng website."],
        ["Phạm vi sử dụng", "Bạn có thể sử dụng website cho mục đích thông tin và liên lạc công việc hợp pháp. Không được can thiệp vào hoạt động, bảo mật hoặc tính sẵn sàng của website."],
        ["Thông tin doanh nghiệp", `Website cung cấp thông tin chính thức về ${company.legalNameVi} nhằm bảo đảm tính minh bạch và phục vụ mục đích tham khảo chung.`],
        ["Quyền sở hữu trí tuệ", "Nội dung, bố cục, hình ảnh và tài liệu gốc trên website thuộc quyền sở hữu hoặc quyền sử dụng của TRIEU HY MEDIA, trừ khi có ghi chú khác. Việc sao chép hoặc tái sử dụng thương mại cần được cho phép."],
        ["Độ chính xác của thông tin", "Công ty cố gắng duy trì thông tin chính xác và cập nhật. Mô tả dịch vụ mang tính khái quát, không phải đề xuất ràng buộc, bảo đảm hoặc tư vấn chuyên môn."],
        ["Liên kết bên ngoài", "Liên kết ngoài được cung cấp để thuận tiện. Công ty không kiểm soát hoặc xác nhận nội dung, bảo mật hay tính sẵn sàng của website bên ngoài."],
        ["Tính sẵn sàng của website", "Công ty có thể bảo trì, cập nhật hoặc tạm ngừng một phần website khi cần thiết. Website không được bảo đảm hoạt động liên tục tuyệt đối."],
        ["Giới hạn trách nhiệm", "Trong phạm vi hợp lý, TRIEU HY MEDIA không chịu trách nhiệm đối với thiệt hại gián tiếp phát sinh chỉ từ việc dựa vào nội dung khái quát hoặc do website tạm thời không khả dụng."],
        ["Thay đổi điều khoản", "Điều khoản có thể được cập nhật khi website hoặc dịch vụ thay đổi. Nội dung cập nhật có hiệu lực từ khi được công bố."],
      ],
    },
  },
  zh: zhContent,
  ko: koContent,
} as const;

export function getContent(locale: Locale) {
  return content[locale];
}
