import { company } from "@/src/config/company";

export const locales = ["en", "vi", "zh"] as const;
export type Locale = (typeof locales)[number];

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}

const shared = {
  en: {
    nav: { home: "Home", about: "About", services: "Services", cocodrama: "CocoDrama", contact: "Contact", contactUs: "Contact us", menu: "Menu", close: "Close" },
    footer: { company: "Company", legal: "Legal", rights: "All rights reserved." },
    labels: {
      legalName: "Legal name",
      legalNameVi: "Vietnamese legal name",
      shortName: "Short name",
      businessId: "Business ID / Tax ID",
      registrationDate: "Registration date",
      status: "Status",
      companyType: "Company type",
      activity: "Primary business activity",
      representative: "Legal representative",
      address: "Address",
      phone: "Phone",
      email: "Email",
      website: "Website",
    },
  },
  vi: {
    nav: { home: "Trang chủ", about: "Giới thiệu", services: "Dịch vụ", cocodrama: "CocoDrama", contact: "Liên hệ", contactUs: "Liên hệ", menu: "Menu", close: "Đóng" },
    footer: { company: "Doanh nghiệp", legal: "Pháp lý", rights: "Bảo lưu mọi quyền." },
    labels: {
      legalName: "Tên pháp nhân",
      legalNameVi: "Tên pháp nhân tiếng Việt",
      shortName: "Tên viết tắt",
      businessId: "Mã số doanh nghiệp / Mã số thuế",
      registrationDate: "Ngày hoạt động",
      status: "Tình trạng",
      companyType: "Loại hình doanh nghiệp",
      activity: "Ngành nghề chính",
      representative: "Người đại diện pháp luật",
      address: "Địa chỉ",
      phone: "Điện thoại",
      email: "Email",
      website: "Website",
    },
  },
  zh: {
    nav: { home: "首页", about: "关于我们", services: "业务服务", cocodrama: "CocoDrama", contact: "联系我们", contactUs: "联系我们", menu: "菜单", close: "关闭" },
    footer: { company: "公司", legal: "法律信息", rights: "版权所有。" },
    labels: {
      legalName: "法定名称",
      legalNameVi: "越南语法定名称",
      shortName: "简称",
      businessId: "企业编号 / 税号",
      registrationDate: "注册日期",
      status: "经营状态",
      companyType: "企业类型",
      activity: "主营业务",
      representative: "法定代表人",
      address: "地址",
      phone: "电话",
      email: "电子邮箱",
      website: "网站",
    },
  },
} as const;

const zhContent = {
  ...shared.zh,
  home: {
    eyebrow: "企业官方网站",
    headline: "以清晰思路打造创意广告",
    intro: `${company.legalNameEn} 是一家位于越南岘港、依法注册的广告公司。我们通过清晰的传播策略、创意内容与务实的广告解决方案，为企业提供支持。`,
    explore: "探索我们的服务",
    overviewTitle: "了解 TRIEU HY MEDIA",
    overview: `${company.legalNameEn} 于 ${company.registrationDateEn} 注册成立，总部位于越南岘港市和春坊。公司专注广告业务，坚持清晰、负责与专业的服务方式。`,
    overviewDetail: "我们的工作环境融合公司办公室、Hỷ Garden 咖啡工作空间，以及 CocoDrama 等数字产品的开发。这一环境支持专注工作、创意交流与务实执行。",
    overviewImage: "TRIEU HY MEDIA 办公空间",
    learnMore: "了解更多",
    hyGarden: {
      eyebrow: "我们的工作环境",
      title: "Hỷ Garden — 办公室与咖啡空间",
      description: "Hỷ Garden 将 TRIEU HY MEDIA 的办公室和咖啡店融于同一空间。这里服务于公司的日常工作，也提供适合专注工作、团队交流和咖啡会谈的区域。",
      note: "一个让工作、沟通和日常连接自然发生的实用空间。",
      labels: ["TRIEU HY MEDIA 办公室", "咖啡工作空间", "花园环境", "楼上工作空间"],
    },
    cocodrama: {
      eyebrow: "数字产品",
      title: "CocoDrama 将本地化短剧带到四个东南亚市场",
      description: "正版影视内容、五种本地化语言，以及通过订阅或广告解锁剧集的灵活观看方式。",
      cta: "探索 CocoDrama",
    },
    servicesTitle: "广告与传播服务",
    servicesIntro: "为需要清晰方向、一致沟通与务实创意执行的企业提供聚焦支持。",
    approachTitle: "我们的工作方式",
    approach: [
      ["了解", "从倾听企业背景、目标与传播需求开始。"],
      ["规划", "明确务实的方向、优先事项和工作范围。"],
      ["创作", "根据共识方向开发传播内容与素材。"],
      ["交付", "谨慎协调交付，并清晰同步进度。"],
      ["复盘", "评估成果并收集反馈，进行适当优化。"],
    ],
    principlesTitle: "工作原则",
    principles: ["清晰", "责任", "一致", "创意", "专业"],
    companyTitle: "企业信息",
    ctaTitle: "让传播更清晰",
    ctaText: "欢迎联系 TRIEU HY MEDIA，咨询广告与企业传播需求。",
    cta: "联系我们的团队",
  },
  about: {
    eyebrow: "关于公司",
    title: "以清晰与责任开展企业传播",
    intro: `${company.legalNameEn} 是一家依法注册、总部位于越南岘港市的越南企业。公司于 ${company.registrationDateEn} 注册，企业编号为 ${company.businessId}。`,
    sections: [
      ["合法设立", "公司为非国有有限责任公司，当前处于正常经营状态，注册地址位于越南岘港市和春坊。"],
      ["主营业务", "公司的注册主营业务是广告，为企业提供务实的广告与传播支持。"],
      ["使命", "通过务实的广告与传播解决方案，帮助企业专业地表达其信息。"],
      ["工作原则", "我们以清晰、责任、一致性并尊重客户目标的方式开展每一个传播项目。"],
    ],
    companyTitle: "官方企业信息",
    contactTitle: "联系信息",
  },
  servicesPage: {
    eyebrow: "我们的服务",
    title: "服务与运营领域",
    intro: "TRIEU HY MEDIA 融合广告与传播支持、CocoDrama 数字产品以及 Hỷ Garden 咖啡工作空间的运营。",
    scope: "支持范围",
    process: "基本流程",
    discuss: "讨论您的项目",
    visualTitle: "从传播服务到数字产品与共享空间",
    visualLabels: ["创意策划与方向", "通过 CocoDrama 传播数字产品"],
  },
  contactPage: {
    eyebrow: "联系我们",
    title: "开启一次清晰的沟通",
    intro: "欢迎就广告与传播服务、CocoDrama、Hỷ Garden 咖啡工作空间或企业官方信息联系 TRIEU HY MEDIA。",
    details: "企业联系信息",
    map: "在 Google 地图中打开地址",
    formTitle: "发送咨询",
    formIntro: "请填写以下表单。若邮件服务尚未配置，我们会提供直接发送邮件的选项，不会显示虚假的成功提示。",
    fields: { name: "姓名", company: "公司", email: "电子邮箱", phone: "电话", subject: "主题", message: "留言内容", consent: "我同意 TRIEU HY MEDIA 使用这些信息回复我的咨询。", submit: "发送咨询", sending: "正在发送…" },
  },
  privacy: {
    title: "隐私政策",
    intro: `本隐私政策说明 ${company.legalNameEn} 如何处理通过官方网站提交的信息。`,
    sections: [
      ["我们收集的信息", "我们可能收集您通过联系表单自愿提供的信息，包括姓名、公司、电子邮箱、电话号码、主题和留言。"],
      ["信息收集目的", "这些信息用于回复咨询、了解业务传播需求、维持相关沟通，并保护网站免受滥用。"],
      ["业务沟通", "我们仅会就您的咨询或正在进行的业务讨论，使用您提供的联系方式与您沟通。"],
      ["数据保留", "咨询信息仅会在沟通、记录保存和合法企业管理所合理需要的期间内保留。"],
      ["Cookie 与分析", "网站目前不使用非必要 Cookie 或广告分析工具。为提供和保护网站，可能会处理必要的技术数据。"],
      ["第三方服务", "托管和邮件服务商可能会在提供服务所需范围内处理有限的技术或表单信息，并适用其自身隐私条款。"],
      ["数据保护", "我们采取合理的管理和技术措施保护已提交的信息；任何互联网传输或存储方式都无法保证绝对安全。"],
      ["您的权利", "在适用义务和合理验证的前提下，您可请求访问、更正或删除已提交的个人信息。"],
      ["外部链接", "本网站链接的外部网站受其自身隐私惯例约束，我们不对其内容或政策负责。"],
      ["政策变更", "我们可能因网站或信息处理方式变更而更新本政策，更新内容发布时将同步更新生效日期。"],
    ],
  },
  terms: {
    title: "使用条款",
    intro: "本使用条款适用于访问和使用 TRIEU HY MEDIA 官方网站。",
    sections: [
      ["接受条款", "使用本网站即表示您同意这些条款；如不同意，请停止使用本网站。"],
      ["允许使用", "您可以将本网站用于合法的信息查询和业务沟通，不得干扰网站的运营、安全或可用性。"],
      ["企业信息", `本网站展示 ${company.legalNameEn} 的官方信息，用于透明披露和一般参考。`],
      ["知识产权", "除非另有说明，网站的文字、版式、图形及其他原创材料均归 TRIEU HY MEDIA 所有或获授权使用；复制或商业再利用须经许可。"],
      ["信息准确性", "我们致力于保持网站信息准确和更新。服务描述仅为一般性说明，不构成有约束力的要约、保证或专业建议。"],
      ["外部链接", "外部网站链接仅为便利提供，我们不控制或认可其内容、安全性或可用性。"],
      ["网站可用性", "在合理必要时，我们可能维护、更新或暂时暂停网站部分内容；不保证持续、不中断的可用性。"],
      ["责任限制", "在合理允许的范围内，TRIEU HY MEDIA 不对仅因依赖一般网站内容或临时不可用而产生的间接损失负责。"],
      ["条款变更", "当网站或服务发生变化时，我们可能更新本条款；更新条款发布后即生效。"],
    ],
  },
} as const;

export const content = {
  en: {
    ...shared.en,
    home: {
      eyebrow: "Official company website",
      headline: "Creative advertising built with clarity",
      intro: `${company.legalNameEn} is a legally registered advertising company based in Da Nang, Vietnam. We support businesses through thoughtful communication, creative content and practical advertising solutions.`,
      explore: "Explore our services",
      overviewTitle: "About TRIEU HY MEDIA",
      overview: `${company.legalNameEn} was registered on ${company.registrationDateEn} and is headquartered in Hoa Xuan Ward, Da Nang City, Vietnam. The company operates in the advertising sector with a commitment to clarity, responsibility and professional service delivery.`,
      overviewDetail: "Our working environment brings together the company office, Hy Garden coffee workspace and the development of digital products such as CocoDrama. This setting supports focused work, creative discussion and practical delivery.",
      overviewImage: "The working office of TRIEU HY MEDIA",
      learnMore: "Learn more about us",
      hyGarden: {
        eyebrow: "Our working environment",
        title: "Hy Garden — office and coffee shop",
        description: "Hy Garden brings together the working office of TRIEU HY MEDIA and a coffee shop within one shared setting. The space supports the company’s daily work while providing areas for focused working sessions, team conversations and time over coffee.",
        note: "A practical environment where work, communication and everyday connection can happen naturally.",
        labels: ["TRIEU HY MEDIA office", "Coffee workspace", "Garden setting", "Upstairs workspace"],
      },
      cocodrama: {
        eyebrow: "Digital product",
        title: "CocoDrama brings localized short-form stories to four Southeast Asian markets",
        description: "Licensed film content, five localization languages and flexible access through subscriptions or advertising-supported episode unlocks.",
        cta: "Explore CocoDrama",
      },
      servicesTitle: "Advertising and communication services",
      servicesIntro: "Focused support for businesses that need clear direction, consistent communication and practical creative execution.",
      approachTitle: "How we work",
      approach: [
        ["Understand", "We begin by listening to the business context, objectives and communication requirements."],
        ["Plan", "We define a practical direction, priorities and a clear scope of work."],
        ["Create", "We develop communication content and materials aligned with the agreed direction."],
        ["Deliver", "We coordinate delivery carefully and communicate progress clearly."],
        ["Review", "We review outcomes and gather feedback for appropriate refinements."],
      ],
      principlesTitle: "Working principles",
      principles: ["Clarity", "Responsibility", "Consistency", "Creativity", "Professionalism"],
      companyTitle: "Company Information",
      ctaTitle: "Let’s create clearer communication",
      ctaText: "Contact TRIEU HY MEDIA for advertising and business communication inquiries.",
      cta: "Contact our team",
    },
    about: {
      eyebrow: "About the company",
      title: "A clear, responsible approach to business communication",
      intro: `${company.legalNameEn} is a legally registered Vietnamese company headquartered in Da Nang City. The company was registered on ${company.registrationDateEn} under Business ID ${company.businessId}.`,
      sections: [
        ["Legal establishment", "The company operates as a non-state limited liability company with active status. Its registered office is located in Hoa Xuan Ward, Da Nang City, Vietnam."],
        ["Main business activity", "The company’s primary registered business activity is Advertising. Our services focus on practical advertising and communication support for businesses."],
        ["Mission", "Our goal is to support businesses in presenting their messages professionally through practical advertising and communication solutions."],
        ["Working principles", "We approach every communication project with clarity, responsibility, consistency and respect for the client’s objectives."],
      ],
      companyTitle: "Official company information",
      contactTitle: "Contact details",
    },
      servicesPage: {
      eyebrow: "Our services",
      title: "Services and operating areas",
      intro: "TRIEU HY MEDIA brings together advertising and communication support, the CocoDrama digital product, and Hy Garden coffee workspace operations.",
      scope: "Scope of support",
      process: "Basic process",
      discuss: "Discuss your project",
      visualTitle: "From communication work to digital products and shared spaces",
      visualLabels: ["Creative planning and direction", "Digital product communication through CocoDrama"],
    },
    contactPage: {
      eyebrow: "Contact",
      title: "Start a clear conversation",
      intro: "Contact TRIEU HY MEDIA regarding advertising and communication support, CocoDrama, Hy Garden coffee workspace or official company inquiries.",
      details: "Company contact details",
      map: "Open address in Google Maps",
      formTitle: "Send an inquiry",
      formIntro: "Complete the form below. If email delivery is not configured, we will provide a direct email option without showing a false success message.",
      fields: { name: "Full name", company: "Company", email: "Email", phone: "Phone", subject: "Subject", message: "Message", consent: "I agree that TRIEU HY MEDIA may use this information to respond to my inquiry.", submit: "Send inquiry", sending: "Sending…" },
    },
    privacy: {
      title: "Privacy Policy",
      intro: `This Privacy Policy explains how ${company.legalNameEn} handles information submitted through this official website.`,
      sections: [
        ["Information we collect", "We may collect the information you choose to provide through the contact form, including your name, company, email address, phone number, subject and message."],
        ["Purpose of data collection", "Information is used to respond to inquiries, understand business communication needs, maintain relevant correspondence and protect the website from misuse."],
        ["Business communication", "We may contact you using the details you provide solely in relation to your inquiry or an ongoing business discussion."],
        ["Data retention", "Inquiry information is retained only for as long as reasonably necessary for communication, record-keeping and legitimate business administration."],
        ["Cookies and analytics", "This website does not currently use non-essential cookies or advertising analytics. Essential technical data may be processed to deliver and secure the website."],
        ["Third-party services", "Hosting and email delivery providers may process limited technical or form information as necessary to provide their services. Their own privacy terms apply."],
        ["Data protection", "We take reasonable administrative and technical measures to protect submitted information. No internet transmission or storage method can be guaranteed as completely secure."],
        ["Your rights", "You may ask us to access, correct or delete personal information you submitted, subject to applicable obligations and reasonable verification."],
        ["External links", "External websites linked from this site are governed by their own privacy practices. We are not responsible for their content or policies."],
        ["Changes to this policy", "We may update this policy to reflect changes to the website or our information practices. The effective date will be updated when changes are published."],
      ],
    },
    terms: {
      title: "Terms of Use",
      intro: "These Terms of Use apply to access and use of the official TRIEU HY MEDIA website.",
      sections: [
        ["Acceptance of terms", "By using this website, you agree to these terms. If you do not agree, please discontinue use of the website."],
        ["Permitted use", "You may use this website for lawful informational and business communication purposes. You must not interfere with its operation, security or availability."],
        ["Company information", `This website presents official information about ${company.legalNameEn}. Company details are provided for transparency and general information.`],
        ["Intellectual property", "Website text, layout, graphics and other original materials are owned by or licensed to TRIEU HY MEDIA unless otherwise stated. Reasonable personal and business reference use is permitted; reproduction or commercial reuse requires permission."],
        ["Accuracy of information", "We aim to keep website information accurate and current. Service descriptions are general and do not constitute a binding proposal, guarantee or professional advice."],
        ["External links", "Links to external websites are provided for convenience. We do not control or endorse their content, security or availability."],
        ["Website availability", "We may maintain, update or temporarily suspend parts of the website when reasonably necessary. Continuous, uninterrupted availability is not guaranteed."],
        ["Limitation of liability", "To the extent reasonably permitted, TRIEU HY MEDIA is not responsible for indirect loss arising solely from reliance on general website content or temporary unavailability."],
        ["Changes to these terms", "We may update these terms when the website or its services change. Updated terms take effect when published."],
      ],
    },
  },
  vi: {
    ...shared.vi,
    home: {
      eyebrow: "Website chính thức của doanh nghiệp",
      headline: "Giải pháp quảng cáo được xây dựng từ sự rõ ràng",
      intro: `${company.legalNameVi} là doanh nghiệp hoạt động trong lĩnh vực quảng cáo tại Thành phố Đà Nẵng, Việt Nam. Công ty hỗ trợ doanh nghiệp thông qua truyền thông rõ ràng, nội dung sáng tạo và các giải pháp quảng cáo thực tế.`,
      explore: "Khám phá dịch vụ",
      overviewTitle: "Giới thiệu TRIEU HY MEDIA",
      overview: `${company.legalNameVi} được đăng ký hoạt động ngày ${company.registrationDateVi} và có trụ sở tại Phường Hòa Xuân, Thành phố Đà Nẵng, Việt Nam. Công ty hoạt động trong lĩnh vực quảng cáo với định hướng rõ ràng, trách nhiệm và chuyên nghiệp.`,
      overviewDetail: "Môi trường làm việc của công ty kết hợp văn phòng, không gian coffee workspace Hỷ Garden và hoạt động phát triển sản phẩm số như CocoDrama. Không gian này hỗ trợ làm việc tập trung, trao đổi sáng tạo và triển khai công việc thực tế.",
      overviewImage: "Văn phòng làm việc của TRIEU HY MEDIA",
      learnMore: "Tìm hiểu thêm về chúng tôi",
      hyGarden: {
        eyebrow: "Không gian làm việc",
        title: "Hỷ Garden — văn phòng làm việc và coffee shop",
        description: "Hỷ Garden kết hợp văn phòng làm việc của TRIEU HY MEDIA và coffee shop trong cùng một không gian. Đây là nơi phục vụ hoạt động làm việc hằng ngày của công ty, đồng thời có các khu vực phù hợp cho làm việc tập trung, trao đổi đội ngũ và những cuộc trò chuyện bên cà phê.",
        note: "Một môi trường thực tế để công việc, giao tiếp và sự kết nối diễn ra tự nhiên.",
        labels: ["Văn phòng TRIEU HY MEDIA", "Không gian coffee workspace", "Khu sân vườn", "Không gian làm việc tầng trên"],
      },
      cocodrama: {
        eyebrow: "Sản phẩm số",
        title: "CocoDrama đưa phim ngắn được bản địa hóa đến bốn thị trường Đông Nam Á",
        description: "Nội dung phim có bản quyền, năm ngôn ngữ bản địa hóa và quyền truy cập linh hoạt qua gói dịch vụ hoặc hình thức mở tập bằng quảng cáo.",
        cta: "Khám phá CocoDrama",
      },
      servicesTitle: "Dịch vụ quảng cáo và truyền thông",
      servicesIntro: "Hỗ trợ tập trung cho doanh nghiệp cần định hướng rõ ràng, truyền thông nhất quán và triển khai sáng tạo thực tế.",
      approachTitle: "Cách chúng tôi làm việc",
      approach: [
        ["Tiếp nhận yêu cầu", "Lắng nghe bối cảnh, mục tiêu và yêu cầu truyền thông của doanh nghiệp."],
        ["Lập kế hoạch", "Xác định định hướng thực tế, thứ tự ưu tiên và phạm vi công việc rõ ràng."],
        ["Phát triển nội dung", "Xây dựng nội dung và tài liệu truyền thông theo định hướng đã thống nhất."],
        ["Triển khai", "Phối hợp bàn giao cẩn trọng và cập nhật tiến độ rõ ràng."],
        ["Đánh giá và phản hồi", "Rà soát kết quả, tiếp nhận phản hồi và hiệu chỉnh phù hợp."],
      ],
      principlesTitle: "Nguyên tắc làm việc",
      principles: ["Rõ ràng", "Trách nhiệm", "Nhất quán", "Sáng tạo", "Chuyên nghiệp"],
      companyTitle: "Thông tin doanh nghiệp",
      ctaTitle: "Cùng tạo nên truyền thông rõ ràng hơn",
      ctaText: "Liên hệ TRIEU HY MEDIA về nhu cầu quảng cáo và truyền thông doanh nghiệp.",
      cta: "Liên hệ đội ngũ",
    },
    about: {
      eyebrow: "Giới thiệu doanh nghiệp",
      title: "Tiếp cận truyền thông doanh nghiệp bằng sự rõ ràng và trách nhiệm",
      intro: `${company.legalNameVi} là doanh nghiệp Việt Nam được đăng ký hợp pháp và có trụ sở tại Thành phố Đà Nẵng. Công ty được đăng ký hoạt động ngày ${company.registrationDateVi} theo mã số doanh nghiệp ${company.businessId}.`,
      sections: [
        ["Thành lập pháp lý", "Công ty hoạt động theo loại hình công ty trách nhiệm hữu hạn ngoài nhà nước, hiện có tình trạng đang hoạt động và đặt trụ sở tại Phường Hòa Xuân, Thành phố Đà Nẵng, Việt Nam."],
        ["Ngành nghề kinh doanh chính", "Ngành nghề kinh doanh chính của công ty là Quảng cáo. Các dịch vụ tập trung vào giải pháp quảng cáo và hỗ trợ truyền thông thực tế cho doanh nghiệp."],
        ["Sứ mệnh", "Mục tiêu của công ty là hỗ trợ doanh nghiệp truyền tải thông điệp chuyên nghiệp thông qua các giải pháp quảng cáo và truyền thông thực tế."],
        ["Nguyên tắc làm việc", "Công ty tiếp cận mỗi hoạt động truyền thông dựa trên sự rõ ràng, trách nhiệm, nhất quán và tôn trọng mục tiêu của khách hàng."],
      ],
      companyTitle: "Thông tin doanh nghiệp chính thức",
      contactTitle: "Thông tin liên hệ",
    },
      servicesPage: {
      eyebrow: "Dịch vụ của chúng tôi",
      title: "Dịch vụ và mảng hoạt động",
      intro: "TRIEU HY MEDIA kết hợp dịch vụ quảng cáo và truyền thông, sản phẩm số CocoDrama cùng hoạt động coffee workspace Hỷ Garden.",
      scope: "Phạm vi hỗ trợ",
      process: "Quy trình cơ bản",
      discuss: "Trao đổi nhu cầu của bạn",
      visualTitle: "Từ truyền thông đến sản phẩm số và không gian chung",
      visualLabels: ["Lập kế hoạch và định hướng sáng tạo", "Truyền thông sản phẩm số qua CocoDrama"],
    },
    contactPage: {
      eyebrow: "Liên hệ",
      title: "Bắt đầu một cuộc trao đổi rõ ràng",
      intro: "Liên hệ TRIEU HY MEDIA về quảng cáo và truyền thông, CocoDrama, Hỷ Garden coffee workspace hoặc thông tin chính thức của doanh nghiệp.",
      details: "Thông tin liên hệ doanh nghiệp",
      map: "Mở địa chỉ trên Google Maps",
      formTitle: "Gửi yêu cầu",
      formIntro: "Hoàn thành biểu mẫu bên dưới. Nếu dịch vụ gửi email chưa được cấu hình, website sẽ cung cấp tùy chọn gửi email trực tiếp và không hiển thị thông báo thành công giả.",
      fields: { name: "Họ và tên", company: "Công ty", email: "Email", phone: "Điện thoại", subject: "Chủ đề", message: "Nội dung", consent: "Tôi đồng ý để TRIEU HY MEDIA sử dụng thông tin này nhằm phản hồi yêu cầu của tôi.", submit: "Gửi yêu cầu", sending: "Đang gửi…" },
    },
    privacy: {
      title: "Chính sách bảo mật",
      intro: `Chính sách này giải thích cách ${company.legalNameVi} xử lý thông tin được gửi qua website chính thức.`,
      sections: [
        ["Thông tin được thu thập", "Công ty có thể thu thập thông tin do bạn chủ động cung cấp qua biểu mẫu liên hệ, gồm họ tên, công ty, email, số điện thoại, chủ đề và nội dung."],
        ["Mục đích thu thập", "Thông tin được sử dụng để phản hồi yêu cầu, tìm hiểu nhu cầu truyền thông, duy trì trao đổi liên quan và bảo vệ website khỏi hành vi lạm dụng."],
        ["Liên lạc công việc", "Công ty có thể liên hệ qua thông tin bạn cung cấp chỉ trong phạm vi yêu cầu hoặc nội dung trao đổi công việc đang diễn ra."],
        ["Thời gian lưu trữ", "Thông tin yêu cầu chỉ được lưu trong thời gian hợp lý cần thiết cho việc trao đổi, lưu hồ sơ và quản trị doanh nghiệp chính đáng."],
        ["Cookie và phân tích", "Website hiện không sử dụng cookie không thiết yếu hoặc công cụ phân tích quảng cáo. Dữ liệu kỹ thuật thiết yếu có thể được xử lý để vận hành và bảo vệ website."],
        ["Dịch vụ bên thứ ba", "Nhà cung cấp dịch vụ lưu trữ và gửi email có thể xử lý một phần dữ liệu kỹ thuật hoặc dữ liệu biểu mẫu khi cần thiết để cung cấp dịch vụ. Chính sách riêng của họ sẽ được áp dụng."],
        ["Bảo vệ dữ liệu", "Công ty áp dụng các biện pháp quản trị và kỹ thuật hợp lý để bảo vệ thông tin. Không phương thức truyền hoặc lưu trữ qua internet nào có thể được bảo đảm an toàn tuyệt đối."],
        ["Quyền của người dùng", "Bạn có thể yêu cầu truy cập, sửa hoặc xóa thông tin cá nhân đã cung cấp, tùy theo nghĩa vụ áp dụng và quy trình xác minh hợp lý."],
        ["Liên kết bên ngoài", "Website bên ngoài được điều chỉnh bởi chính sách riêng của họ. Công ty không chịu trách nhiệm về nội dung hoặc chính sách của các website đó."],
        ["Thay đổi chính sách", "Chính sách có thể được cập nhật khi website hoặc cách xử lý thông tin thay đổi. Ngày hiệu lực sẽ được cập nhật khi nội dung mới được công bố."],
      ],
    },
    terms: {
      title: "Điều khoản sử dụng",
      intro: "Điều khoản này áp dụng khi truy cập và sử dụng website chính thức của TRIEU HY MEDIA.",
      sections: [
        ["Chấp nhận điều khoản", "Khi sử dụng website, bạn đồng ý với các điều khoản này. Nếu không đồng ý, vui lòng ngừng sử dụng website."],
        ["Phạm vi sử dụng", "Bạn có thể sử dụng website cho mục đích thông tin và liên lạc công việc hợp pháp. Không được can thiệp vào hoạt động, bảo mật hoặc tính sẵn sàng của website."],
        ["Thông tin doanh nghiệp", `Website cung cấp thông tin chính thức về ${company.legalNameVi} nhằm bảo đảm tính minh bạch và phục vụ mục đích tham khảo chung.`],
        ["Quyền sở hữu trí tuệ", "Nội dung, bố cục, hình ảnh và tài liệu gốc trên website thuộc quyền sở hữu hoặc quyền sử dụng của TRIEU HY MEDIA, trừ khi có ghi chú khác. Việc sao chép hoặc tái sử dụng thương mại cần được cho phép."],
        ["Độ chính xác của thông tin", "Công ty cố gắng duy trì thông tin chính xác và cập nhật. Mô tả dịch vụ mang tính khái quát, không phải đề xuất ràng buộc, bảo đảm hoặc tư vấn chuyên môn."],
        ["Liên kết bên ngoài", "Liên kết ngoài được cung cấp để thuận tiện. Công ty không kiểm soát hoặc xác nhận nội dung, bảo mật hay tính sẵn sàng của website bên ngoài."],
        ["Tính sẵn sàng của website", "Công ty có thể bảo trì, cập nhật hoặc tạm ngừng một phần website khi cần thiết. Website không được bảo đảm hoạt động liên tục tuyệt đối."],
        ["Giới hạn trách nhiệm", "Trong phạm vi hợp lý, TRIEU HY MEDIA không chịu trách nhiệm đối với thiệt hại gián tiếp phát sinh chỉ từ việc dựa vào nội dung khái quát hoặc do website tạm thời không khả dụng."],
        ["Thay đổi điều khoản", "Điều khoản có thể được cập nhật khi website hoặc dịch vụ thay đổi. Nội dung cập nhật có hiệu lực từ khi được công bố."],
      ],
    },
  },
  zh: zhContent,
} as const;

export function getContent(locale: Locale) {
  return content[locale];
}
